add: menambahkan contoh penggunaan some
bellshade/Javascript pull request #12
Opened 2021-09-10 13:32 UTC by reacto11mecha

## deskripsi (description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya memperbaiki dokumentasi
- [x] saya menambah dokumentasi

## contributor requirements (syarat contributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## env

saya menggunakan (im used):

- `os` = `linux`

## testing

- [x] doctesting js
- [x] lint testing eslint

## maintainer

@amdev142
@nomadkode

2021-09-10 14:41 UTC, nomadkode approved these changes
aight, LGTM 👍🏼

2021-09-10 14:42 UTC, hendraaagil approved these changes

2021-09-10 15:09 UTC, itsfaqih requested changes

2021-09-10 15:09 UTC, itsfaqih commented on other/someValueInArray.js
> +let isiDapurTiga = ["sodet", "cangkir"];
```suggestion
const isiDapurSatu = ["panci", "penggorengan", "garpu"];
const isiDapurDua = ["garpu", "gelas", "sendok"];
const isiDapurTiga = ["sodet", "cangkir"];
```
karena berisi `array` dan nilainya tidak berubah, lebih baik menggunakan `const`.
sekaligus bisa memberikan contoh practice yang baik

2021-09-10 15:12 UTC, reacto11mecha commented on other/someValueInArray.js
> +let isiDapurTiga = ["sodet", "cangkir"];
Oke besok pagi ku ubah, abis batre laptop ku

2021-09-11 00:23 UTC, slowy07 approved these changes

2021-09-11 00:27 UTC, reacto11mecha commented
done

2021-09-11 04:05 UTC, itsfaqih approved these changes

2021-09-11 06:16 UTC, reacto11mecha commented
umm. udah bisa di merge ?

2021-09-11 07:00 UTC, merged