UI server, memperbarui script dan update hal kecil lainnya
bellshade/Javascript pull request #171
Opened 2021-10-25 07:11 UTC by reacto11mecha

Closes #164 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [x] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux`

## Testing

- [ ] doctesting js
- [x] lint testing eslint

2021-10-31 03:02 UTC, reacto11mecha commented
Hmmm, kayaknya mesti diganti pendekatan si pathnya dibentuk. Bakalan ganti ke fastify soalnya route dia bisa di foreach, jadi data pathnya bisa murni di dapetin dari data yang di foreach

https://github.com/mihneadb/node-directory-tree mungkin ini bisa dipake buat read directorynya

2021-11-02 01:23 UTC, reacto11mecha commented
Update, sekarang file html sama js yang di folder dom sama web api bisa di preview langsung ditambah output dari si console bisa di liat langsung, sekalian ada mini code editor. Makasih buat om @wahyall yang udah bikin layout dasar buat code editornya.

![image](https://user-images.githubusercontent.com/48118327/139771108-1bcc8b01-a35f-4081-8671-5f60042caa6f.png)
![image](https://user-images.githubusercontent.com/48118327/139771128-4537e629-393e-49d8-9e40-0f5e0685cc6e.png)
![image](https://user-images.githubusercontent.com/48118327/139771153-3c861619-7458-436e-b827-978c3d890f8b.png)

Interaksi langsung di iframe
![image](https://user-images.githubusercontent.com/48118327/139771228-d9b71119-583f-49a1-97ae-188bd831e8f7.png)

Output console dari iframe
![image](https://user-images.githubusercontent.com/48118327/139771577-c57a2ca1-de93-46f8-87c8-ef6539d32f60.png)

Ketambahan library prismjs, tinggal jalanin install kayak biasa
```bash
npm install
```

2021-11-02 03:15 UTC, azqilana commented
> Update, sekarang file html sama js yang di folder dom sama web api bisa di preview langsung ditambah output dari si console bisa di liat langsung, sekalian ada mini code editor. Makasih buat om @wahyall yang udah bikin layout dasar buat code editornya.
> 
> ![image](https://user-images.githubusercontent.com/48118327/139771108-1bcc8b01-a35f-4081-8671-5f60042caa6f.png) ![image](https://user-images.githubusercontent.com/48118327/139771128-4537e629-393e-49d8-9e40-0f5e0685cc6e.png) ![image](https://user-images.githubusercontent.com/48118327/139771153-3c861619-7458-436e-b827-978c3d890f8b.png)
> 
> Interaksi langsung di iframe ![image](https://user-images.githubusercontent.com/48118327/139771228-d9b71119-583f-49a1-97ae-188bd831e8f7.png)
> 
> Output console dari iframe ![image](https://user-images.githubusercontent.com/48118327/139771577-c57a2ca1-de93-46f8-87c8-ef6539d32f60.png)
> 
> Ketambahan library prismjs, tinggal jalanin install kayak biasa
> 
> ```shell
> npm install
> ```

seneng banget saya lihat nya udah saya coba

2021-11-03 15:38 UTC, reacto11mecha commented
Note for my self, tambahin di contributing, tambahin di head

```html
<script>
  const _log = console.log;
  console.log = function (...rest) {
    window.parent.postMessage(
      {
        source: "iframe",
        message: rest
      },
      "*"
    );
    _log.apply(console, arguments);
  };
</script>
```

2021-11-08 15:36 UTC, reacto11mecha commented
> saya coba tadi tp masih ada yang tidak jalan kodenya

Bagian yang mana tuh om ?

2021-11-08 15:39 UTC, azqilana commented
> > saya coba tadi tp masih ada yang tidak jalan kodenya
> 
> Bagian yang mana tuh om ?

waktu kita saya masukin folder lain saya masukin folder dom method  code dari folder itu nggakk jalan dengan baik kkarena console.log

2021-11-08 15:58 UTC, reacto11mecha commented
> > > saya coba tadi tp masih ada yang tidak jalan kodenya
> > 
> > 
> > Bagian yang mana tuh om ?
> 
> waktu saya masukin folder lain saya masukin folder dom method dan code dari folder itu nggakk jalan dengan baik karena console.log yang error

ada video langkah langkah gimana om ngelakuinnya ga ? kalo dikasih tau gini doang ga tau gimana errornya, sekalian juga kasih tau filenya gimana biar bisa ngasi tau fixnya

2021-11-08 15:59 UTC, azqilana commented
> > > > saya coba tadi tp masih ada yang tidak jalan kodenya
> > > 
> > > 
> > > Bagian yang mana tuh om ?
> > 
> > 
> > waktu saya masukin folder lain saya masukin folder dom method dan code dari folder itu nggakk jalan dengan baik karena console.log yang error
> 
> ada video langkah langkah gimana om ngelakuinnya ga ? kalo dikasih tau gini doang ga tau gimana errornya, sekalian juga kasih tau filenya gimana biar bisa ngasi tau fixnya

nanti saya videoin ya

2021-11-08 16:17 UTC, azqilana commented
https://user-images.githubusercontent.com/27930710/140777613-28e4198e-cdb4-4117-aae4-f8f8ad3aeebe.mp4

2021-11-08 22:55 UTC, azqilana commented
> > bandicam.2021-11-09.00-05-33-832.mp4
> > ini om videonya om @reacto11mecha
> 
> Ooh ini sebenernya udah dibenerin, sekarang om pull dulu baru bisa ngejalanin perubahan terbaru
> 
> ```shell
> git pull
> ```
> 
> Udah ketambahan juga kok yang methods, udah dibenerin juga teknik nangkep pesannya kayak gimana

dari kemarin coba git pull tida bisa om

2021-11-13 05:53 UTC, azqilana approved these changes
LGTM

2021-11-14 01:52 UTC, hasheemi requested changes
maaf baru coba,
di halaman home bagian jalur markdown table tidak berfungsi 
kalau style halaman setiap materi mungkin menurut saya tema diperbagus sedikit

2021-11-14 02:36 UTC, reacto11mecha commented
> maaf baru coba, di halaman home bagian jalur markdown table tidak berfungsi kalau style halaman setiap materi mungkin menurut saya tema diperbagus sedikit

Hmm, ada petunjuk halaman materi lain ? Maksudnya mau diperbagus kayak gimananya gitu

2021-11-14 03:01 UTC, hasheemi commented
> > maaf baru coba, di halaman home bagian jalur markdown table tidak berfungsi kalau style halaman setiap materi mungkin menurut saya tema diperbagus sedikit
> 
> Hmm, ada petunjuk halaman materi lain ? Maksudnya mau diperbagus kayak gimananya gitu

kalau halaman lain sih boleh aja kayak pagination gitu ,

2021-11-14 03:09 UTC, azqilana commented
> > > maaf baru coba, di halaman home bagian jalur markdown table tidak berfungsi kalau style halaman setiap materi mungkin menurut saya tema diperbagus sedikit
> > 
> > 
> > Hmm, ada petunjuk halaman materi lain ? Maksudnya mau diperbagus kayak gimananya gitu
> 
> kalau halaman lain sih boleh aja kayak pagination gitu ,

jadi mau di buat pagination gitu

2021-11-14 04:58 UTC, reacto11mecha commented
> > > maaf baru coba, di halaman home bagian jalur markdown table tidak berfungsi kalau style halaman setiap materi mungkin menurut saya tema diperbagus sedikit
> > 
> > 
> > Hmm, ada petunjuk halaman materi lain ? Maksudnya mau diperbagus kayak gimananya gitu
> 
> kalau halaman lain sih boleh aja kayak pagination gitu ,

Mungkin masalah pagination bisa di tambahin nanti, mungkin iterasi selanjutnya. Fokusnya sekarang jadi dulu sama fitur fitur dasar dah jadi dulu kayak web viewer repo php.

Dan juga makasih dah ngasih tau kalo table readme rootnya bermasalah, ku fix sore ini

2021-11-15 10:02 UTC, wahyall commented
> maaf baru coba, di halaman home bagian jalur markdown table tidak berfungsi kalau style halaman setiap materi mungkin menurut saya tema diperbagus sedikit

Utk style ngikut menurut saya cukup sprti itu dulu aja om, yg penting fungsionalitasnya jalan dulu sprti repo php

2021-11-16 12:11 UTC, reacto11mecha commented
![image](https://user-images.githubusercontent.com/48118327/141983106-9a499087-47a0-473f-9e34-fb3fc84286c6.png)

Untuk masalah table di root sudah diperbaiki, tinggal dikasih jarak aja ternyata kalo di marked js

2021-11-16 12:16 UTC, hasheemi approved these changes
Sip kalau gitu kayak nya udah semua

2021-11-16 20:18 UTC, nomadkode commented
yaml nya bagian label perlu di edit ada bot mergefy yg error karena sudah gak ada tim docs.

2021-11-16 22:22 UTC, reacto11mecha commented
> yaml nya bagian label perlu di edit ada bot mergefy yg error karena sudah gak ada tim docs.

Okey, sekalian sama yang ini

2021-11-17 00:48 UTC, reacto11mecha commented
> yaml nya bagian label perlu di edit ada bot mergefy yg error karena sudah gak ada tim docs.

Selesai om, silahkan di review

2021-11-17 13:11 UTC, nomadkode commented
> > yaml nya bagian label perlu di edit ada bot mergefy yg error karena sudah gak ada tim docs.
> 
> Selesai om, silahkan di review

Udah oke sih harusnya. Cuma masih error. Help @slowy07

2021-11-17 13:14 UTC, reacto11mecha commented
> > > yaml nya bagian label perlu di edit ada bot mergefy yg error karena sudah gak ada tim docs.
> > 
> > 
> > Selesai om, silahkan di review
> 
> Udah oke sih harusnya. Cuma masih error. Help @slowy07

Kalo buat rule aman sih harusnya, dia perlu di merge dulu biar bisa kepake. Yang masalah aku ga ngerti di bagian node ci, kenapa dia failed

2021-11-18 05:26 UTC, nomadkode commented
> > > > yaml nya bagian label perlu di edit ada bot mergefy yg error karena sudah gak ada tim docs.
> > > 
> > > 
> > > Selesai om, silahkan di review
> > 
> > Udah oke sih harusnya. Cuma masih error. Help @slowy07
> 
> Kalo buat rule aman sih harusnya, dia perlu di merge dulu biar bisa kepake. Yang masalah aku ga ngerti di bagian node ci, kenapa dia failed

Yaudah merge aja zra, kalo masih error bisa di solve nanti.

2021-11-18 05:28 UTC, reacto11mecha commented
> > > > > yaml nya bagian label perlu di edit ada bot mergefy yg error karena sudah gak ada tim docs.
> > > > 
> > > > 
> > > > Selesai om, silahkan di review
> > > 
> > > 
> > > Udah oke sih harusnya. Cuma masih error. Help @slowy07
> > 
> > 
> > Kalo buat rule aman sih harusnya, dia perlu di merge dulu biar bisa kepake. Yang masalah aku ga ngerti di bagian node ci, kenapa dia failed
> 
> Yaudah merge aja zra, kalo masih error bisa di solve nanti.

Approve dulu om, terus kasih label. Dah aman kan docs nya

2021-11-18 09:26 UTC, nomadkode approved these changes

2021-11-18 09:35 UTC, dhafitf commented
Waduh baru aja nemu yang salah om

2021-11-18 09:57 UTC, wahyall approved these changes

2021-11-18 10:02 UTC, reacto11mecha commented
Node CI nya failed jadi walaupun di kasih label `ready-to-merge` ga bakalan bisa. Mesti di merge manual

2021-11-18 10:26 UTC, nomadkode commented
> Node CI nya failed jadi walaupun di kasih label `ready-to-merge` ga bakalan bisa. Mesti di merge manual

ngebuildnya masih failed yaa brarti?

2021-11-18 11:10 UTC, reacto11mecha commented
> > Node CI nya failed jadi walaupun di kasih label `ready-to-merge` ga bakalan bisa. Mesti di merge manual
> 
> ngebuildnya masih failed yaa brarti?

Hooh

2021-11-18 11:53 UTC, rizkyikhwan approved these changes
baru ada waktu buat nyobain ini tadi, LGTM om

2021-11-18 22:07 UTC, nomadkode commented
> > > Node CI nya failed jadi walaupun di kasih label `ready-to-merge` ga bakalan bisa. Mesti di merge manual
> > 
> > ngebuildnya masih failed yaa brarti?
> 
> Hooh

Jadi mau di merge dulu apa solve dulu nih masalah node CI nya? Kan bisa force merge pake manual kan.

2021-11-18 22:43 UTC, reacto11mecha commented
> > > > Node CI nya failed jadi walaupun di kasih label `ready-to-merge` ga bakalan bisa. Mesti di merge manual
> > > 
> > > 
> > > ngebuildnya masih failed yaa brarti?
> > 
> > 
> > Hooh
> 
> Jadi mau di merge dulu apa solve dulu nih masalah node CI nya? Kan bisa force merge pake manual kan.

Merge aja dulu, bisa di solve nanti

2021-11-19 01:16 UTC, merged