feat:Menambahkan Materi DOM - Methods bag 1
bellshade/Javascript pull request #184
Opened 2021-11-01 15:32 UTC by azqilana

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [ ] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux / windows / macOS`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

## Maintainer

2021-11-01 15:35 UTC, azqilana commented
maaf sebelumnya materi ini belum selesai jadi belum waktunya unutk di merge

2021-11-01 15:43 UTC, dhafitf commented
Kalau belum selesai, saya ubah jadi draft dulu ya.

2021-11-01 15:44 UTC, azqilana commented
> Kalau belum selesai, saya ubah jadi draft dulu ya.

iya om @dhafitf

2021-11-02 16:17 UTC, azqilana commented
maaf om @reacto11mecha @dhafitf  dan semuanya saya  sempet salah commit dan kepush  karena kurang fokus

2021-11-03 02:27 UTC, dhafitf commented
Untuk kedepannya, dalam mengetikan materi mohon diperhatikan penulisan huruf kapitalnya. Saya koreksi lumayan banyak tuh di commit [docs: memperbaiki penulisan materi](https://github.com/bellshade/Javascript/pull/184/commits/29b3d6face660dc1ae486b864af34bc1d85ab7ff).

2021-11-03 02:35 UTC, dhafitf commented on learn/DOM/003_Collections/script.js
> +// seluruh elemen dengan class condog
```suggestion
// seluruh elemen dengan class condong
```

2021-11-03 02:35 UTC, dhafitf commented on learn/DOM/004_Methods/Readme.md
> +> Selain Method/Fungsi yang di atas masih ada fungsi lain lagi yang dapat di gunakan untuk memanipulasi sebuah element tapi method /fungsi yang di ataslah yang saya tau banyak di gunakan.
Sebaiknya ini dihilangkan saja, karena dapat membuat orang yang akan belajar bertanya-tanya tentang materi ini.

2021-11-03 02:57 UTC, reacto11mecha requested changes
Nama file readmenya jangan `Readme.md`, yang bener `README.md`

2021-11-03 02:57 UTC, reacto11mecha commented on learn/DOM/004_Methods/index.html
> +
Harusnya susunan htmlnya kayak gini, terus juga karena di file js ada syntax `console.log`, biar ga ribet nanti di #171, langsung tambahin aja fungsi yang ngirim pesan ke parent

```suggestion
   <script>
      const _log = console.log;
      console.log = function (...rest) {
        window.parent.postMessage(
          {
            source: "iframe",
            message: rest
          },
          "*"
        );
        _log.apply(console, arguments);
      };
    </script>
    
    <style>
        div {
            border: 2px solid blue;
            margin: 10px auto;
            text-align: center;
            padding: 10px;
        }
        .gradient{
            background: linear-gradient(to bottom, blue , yellow , red );
            border-radius: 10px;
            border-color: transparent;
        }
    </style>

    <title>DOM Methods</title>
</head>
```

2021-11-03 03:36 UTC, azqilana commented on learn/DOM/004_Methods/index.html
> +
apa di file javascriptnya say hapus console.lognya

2021-11-03 03:44 UTC, reacto11mecha commented on learn/DOM/004_Methods/index.html
> +
`console.log` mah biarin aja, tambahin yang ini aja

2021-11-03 03:50 UTC, azqilana commented on learn/DOM/004_Methods/index.html
> +
java script di atas tag style udah di tambahin

2021-11-03 05:22 UTC, azqilana commented on learn/DOM/004_Methods/index.html
> +
![bandicam 2021-11-03 13-21-24-817](https://user-images.githubusercontent.com/27930710/140013244-294547b7-d435-4e83-856d-4ced37dd123e.jpg)
sudah di tambahkan text javascriptnya ya om

2021-11-03 06:22 UTC, reacto11mecha approved these changes
Sip om, lgtm 👍

2021-11-03 06:24 UTC, azqilana commented
beberapa ini saya  banyak pikiran om @reacto11mecha  makanya banyak eror dan banyak  kali rebase commit dr kemarin

2021-11-03 06:26 UTC, reacto11mecha commented
> beberapa hari ini saya  banyak pikiran om @reacto11mecha  makanya banyak eror dan banyak  kali rebase commit dr kemarin 
> mikirin tugas kuliah 

Hmm, yaudah kuliah aja didepankan dulu, yang ini bisa nanti. Kalo emang mau nyelesain yang revisi saat ini nanti jadiin draft pr aja lagi

2021-11-03 06:28 UTC, hendraaagil approved these changes

2021-11-03 06:29 UTC, azqilana commented
> > beberapa hari ini saya  banyak pikiran om @reacto11mecha  makanya banyak eror dan banyak  kali rebase commit dr kemarin
> > mikirin tugas kuliah
> 
> Hmm, yaudah kuliah aja didepankan dulu, yang ini bisa nanti. Kalo emang mau nyelesain yang revisi saat ini nanti jadiin draft pr aja lagi

materinya udah selesai om 
tinggal tunggu hasilnya aja di merge atau bagaimn

2021-11-03 06:29 UTC, reacto11mecha commented
> > > beberapa hari ini saya  banyak pikiran om @reacto11mecha  makanya banyak eror dan banyak  kali rebase commit dr kemarin
> > > mikirin tugas kuliah
> > 
> > Hmm, yaudah kuliah aja didepankan dulu, yang ini bisa nanti. Kalo emang mau nyelesain yang revisi saat ini nanti jadiin draft pr aja lagi
> 
> materinya udah selesai om 
> tinggal tunggu hasilnya aja di merge atau bagaimn 

Ooo okey

2021-11-03 06:34 UTC, reacto11mecha commented on learn/DOM/003_Collections/script.js
> +// seluruh elemen dengan class condog
Yang ini pr sebelumnya, diubah aja om soalnya pr ini aslinya buat yang dom methods doang

2021-11-03 08:59 UTC, nomadkode approved these changes
LGTM

2021-11-03 09:00 UTC, merged

2021-11-03 09:00 UTC, nomadkode commented
kok masih request review tim docs sih wkwkwk @reacto11mecha @slowy07

2021-11-03 09:07 UTC, reacto11mecha commented
> kok masih request review tim docs sih wkwkwk @reacto11mecha @slowy07 
> 

Dunno