Improvisasi README dan Refactoring Struktur Folder
bellshade/Javascript pull request #192
Opened 2021-11-06 12:41 UTC by wahyall

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [x] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

## Maintainer

2021-11-06 12:43 UTC, reacto11mecha commented
Kayaknya rame amat yang di tag jadi reviewer

2021-11-06 12:44 UTC, wahyall commented
> Kayaknya rame amat yang di tag jadi reviewer

jadi gimana? aman aja kan harusnya

2021-11-06 12:49 UTC, reacto11mecha reviewed
Untuk penggunaan si #171 sengaja ga sekalian aja om ? Kalo nanti juga gapapa sih

2021-11-06 12:50 UTC, reacto11mecha commented
> > Kayaknya rame amat yang di tag jadi reviewer
> 
> jadi gimana? aman aja kan harusnya

Aman aja, tapi nanti perlu dirubah buat siapa aja yang dipanggilnya

2021-11-06 12:56 UTC, wahyall commented
> Untuk penggunaan si #171 sengaja ga sekalian aja om ? Kalo nanti juga gapapa sih

iya nanti aja om

2021-11-06 13:00 UTC, reacto11mecha approved these changes
Ya udah om, dah bagus ini :+1:

2021-11-06 13:55 UTC, hasheemi approved these changes
Sudah bagus sih silabus nya, sip LGTM 👍

2021-11-06 14:14 UTC, rizkyikhwan approved these changes
LGTM🚀

2021-11-06 14:17 UTC, azqilana requested changes
kasih saran tukar tempat Event Bubling dengan Traversal

2021-11-06 14:18 UTC, wanrabbae approved these changes
LGTM 🚀

2021-11-06 14:20 UTC, azqilana requested changes

2021-11-06 14:20 UTC, azqilana commented on README.md
> +| 07 | Event Bubbling | Memahami lebih dalam mengenai _events_ dan _method-method_ di dalamnya | [WPU - Event Bubbling](https://youtu.be/a_JFfPHTAf4) |
boleh kasih saran jika mengikuti alur playlist pak dika di Alur DOM nya itu Traversal di taruh sebelum event bubling om jadi boleh minta tolong untuk ganti sedikit yang nomor 7 itu traversal terus yang nomor 8 event bublingnya

2021-11-06 14:27 UTC, hasheemi reviewed
Kalau boleh saran di folder algoritmn other bisa di pisah lagi ke number dan other , saya lihat algoritma nya banyak yang memanipulasi angka, bagaimana bang @reacto11mecha

2021-11-06 14:29 UTC, reacto11mecha commented
> Kalau boleh saran di folder algoritmn other bisa di pisah lagi ke number dan other , saya lihat algoritma nya banyak yang memanipulasi angka, bagaimana bang @reacto11mecha

Yang mana tuh ?

2021-11-07 00:14 UTC, hasheemi commented
> > Kalau boleh saran di folder algoritmn other bisa di pisah lagi ke number dan other , saya lihat algoritma nya banyak yang memanipulasi angka, bagaimana bang @reacto11mecha
> 
> Yang mana tuh ?

Yang ada di folder algoritmn kan ada folder other, karena saya lihat banyak yang berisi algoritma memanipulasi angka, apakah bisa dipisah ke folder baru / number supaya lebih bagus

2021-11-07 03:55 UTC, azqilana approved these changes
terima kasih  LGTM

2021-11-07 04:49 UTC, Vins2106 approved these changes
LGTM, Mantap

2021-11-07 10:26 UTC, AdhyWiranto44 commented
@reacto11mecha om udah beres kayaknya ini, bisa dikasih label merge

2021-11-07 11:19 UTC, reacto11mecha commented
Hmm oke, saatnya nambah label

2021-11-07 11:19 UTC, merged

2021-11-07 13:11 UTC, nomadkode reviewed
LGTM 🚀