DOM  Event Bubbling And Capturing
bellshade/Javascript pull request #194
Opened 2021-11-08 04:00 UTC by azqilana

Closes #154 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows `

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

## Maintainer

2021-11-08 04:02 UTC, azqilana commented
Tolong Jadikan Draft

2021-11-13 06:52 UTC, wahyall approved these changes
Siip om, LGTM :100:

2021-11-13 06:58 UTC, reacto11mecha approved these changes

2021-11-13 08:47 UTC, rizkyikhwan approved these changes

2021-11-13 16:17 UTC, nomadkode requested changes
Bisa diperbaiki lagi yaa om sesuai suggestion nya @azqilana

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +> *Event Bubbling* ialah saat dimana event/aksi yang di berikan pada sebuah element juga memicu atau menjalankan event/aksi yang di berikan kepada element pembungkusnya (*parentElement*), jadi sesuai
```suggestion
> *Event Bubbling* ialah saat dimana event/aksi yang di berikan pada sebuah element juga memicu atau menjalankan event/aksi yang di berikan kepada element pembungkusnya (*parentElement*), jadi sesuai dengan namanya _Bubbling_ gelembung maka event/aksi nya akan menggelembung ke element pembungkusnya (*parentElement*).
```

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Diatas saya ada sebuah `<div>` yang berisi `<div>` dan `<h3>` yang di dalam `<div>` ada `<div>` yang di dalamnya  ada  `<div>` juga , kali ini saya akan menunjukan event bubbling yang terjadi pada el
```suggestion
Diatas saya ada sebuah `<div>` yang berisi `<div>` dan `<h3>` yang di dalam `<div>` ada `<div>` yang di dalamnya  ada  `<div>` juga , kali ini saya akan menunjukkan event bubbling yang terjadi pada element element di atas. 
```

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +jadi kita akan memberikan event kesetiap `<div>` mulai dari yang punya class bub1 sampai yang punya class bub3.
```suggestion
jadi kita akan memberikan event ke setiap `<div>` mulai dari class bub1 sampai class bub3.
```

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Hasil ketika di beri aksi/event dapat di lihat pada gift di bawah
```suggestion
Hasil ketika di beri aksi/event dapat di lihat pada gif di bawah ini :
```

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Pada gift diatas sudah kita lihat pada console bahwa setelah menjalanan event pada variabel bu3 javascript juga menjalankan event pada element pembungkus (*parentElement*) dari bu3 dan begitu seterus
```suggestion
Pada gif diatas dapat kita lihat pada console bahwa setelah menjalankan event pada variabel bu3 javascript juga menjalankan event pada element pembungkus (*parentElement*) dari bu3 dan begitu seterusnya sampai eventnya berhenti pada varibel bu1 dan itu dapat terlihat jelas dengan hasil console yang mencetak hasil console dari bu3 terlebih dahulu kemudian bu2 terus yang terakhir bu1 yang di mana bu1 ini variabel yang merupakan hasil inisialisasi dari element div yang memiliki class bub1 yang merupakan pembungkus dari `<div>` yang memiliki class bub2.
```

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Tapi *Event Bubbling* dapat menjadi masalah jika kita menginginkan eventnya berjalan saat element itu sendiri yang di klik, dan tidak ingin eventnya berjalan saat mengklik event yang ada di dalamnya,
```suggestion
Tapi *Event Bubbling* dapat menjadi masalah jika kita menginginkan eventnya berjalan saat element itu sendiri yang di klik, dan tidak ingin eventnya berjalan saat mengklik event yang ada di dalamnya. Untuk mengatasinya dapat memberikan *event.stopPropagation();* yang berfungsi menjalankan event pada element yang di klik.
```

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Hasil ketika di beri aksi/event dapat di lihat pada gift di bawah
```suggestion
Hasil ketika di beri aksi/event dapat di lihat pada gif di bawah ini :
```

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Pada gift diatas sudah kita lihat pada console bahwa setelah menjalankan event pada variabel anbu3 javascript tidak lagi menjalankan event pada element pembungkus (*parentElement*) dari anbu3 dan beg
```suggestion
Pada gif diatas sudah kita lihat pada console bahwa setelah menjalankan event pada variabel anbu3 javascript tidak lagi menjalankan event pada element pembungkus (*parentElement*) dari anbu3 dan begitu seterusnya dapat terlihat jelas dengan hasil console yang mencetak hasil console dari anbu3 dan tidak kemudian memberi aksi/event pada anbu2 sampai anbu2 di beri aksi/event baru hasil console nya  di jalankan dan begitupun yang terjadi pada hasil console dari anbu yang di jalankan setelah di beri aksi/event.
```

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Jadi di atas saya ada element yang susunannya sama seperti element pada contoh pertama hanya berbeda nama class nya saja pada element di atas saya akan melakukan hal yang sama seperti pada contoh per
gimana maksudnya?

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +* kedua kita berikan aksi/event pada setiap `<div>`,tapi pada kali ini saya akan memberikan nilai bollean `true` pada setiap event nya nilai true ini memiliki arti bahwa event capture nya bernilai tr
```suggestion
* kedua kita berikan aksi/event pada setiap `<div>` tapi pada kali ini saya akan memberikan nilai boolean `true` pada setiap event nya. Nilai true ini memiliki arti bahwa event capture nya bernilai true atau berlaku pada event yang diberikan element tersebut
```

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Hasil ketika di beri aksi/event dapat di lihat pada gift di bawah
```suggestion
Hasil ketika di beri aksi/event dapat di lihat pada gif di bawah ini :
```

2021-11-13 16:17 UTC, nomadkode commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Pada gift diatas sudah kita lihat pada console bahwa javascript menangkap dan menjalankan terlebih dahulu event dari pembungkus terluarnya baru setelah itu menjalankan event pada child nya.
```suggestion
Pada gif diatas dapat kita lihat pada console bahwa javascript menangkap dan menjalankan terlebih dahulu event dari pembungkus terluarnya baru setelah itu menjalankan event pada child nya.
```

2021-11-13 16:52 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +> *Event Bubbling* ialah saat dimana event/aksi yang di berikan pada sebuah element juga memicu atau menjalankan event/aksi yang di berikan kepada element pembungkusnya (*parentElement*), jadi sesuai
sudah di ganti om silahkan di periksa

2021-11-13 16:52 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Diatas saya ada sebuah `<div>` yang berisi `<div>` dan `<h3>` yang di dalam `<div>` ada `<div>` yang di dalamnya  ada  `<div>` juga , kali ini saya akan menunjukan event bubbling yang terjadi pada el
sudah di ganti om silahkan di periksa

2021-11-13 16:52 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +jadi kita akan memberikan event kesetiap `<div>` mulai dari yang punya class bub1 sampai yang punya class bub3.
sudah di ganti om silahkan di periksa

2021-11-13 16:52 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Hasil ketika di beri aksi/event dapat di lihat pada gift di bawah
sudah di ganti om silahkan di periksa

2021-11-13 16:53 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Pada gift diatas sudah kita lihat pada console bahwa setelah menjalanan event pada variabel bu3 javascript juga menjalankan event pada element pembungkus (*parentElement*) dari bu3 dan begitu seterus
sudah di ganti om silahkan di periksa

2021-11-13 16:53 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Tapi *Event Bubbling* dapat menjadi masalah jika kita menginginkan eventnya berjalan saat element itu sendiri yang di klik, dan tidak ingin eventnya berjalan saat mengklik event yang ada di dalamnya,
sudah di ganti om silahkan di periksa

2021-11-13 16:53 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Hasil ketika di beri aksi/event dapat di lihat pada gift di bawah
sudah di ganti om silahkan di periksa

2021-11-13 16:53 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Pada gift diatas sudah kita lihat pada console bahwa setelah menjalankan event pada variabel anbu3 javascript tidak lagi menjalankan event pada element pembungkus (*parentElement*) dari anbu3 dan beg
sudah di ganti om silahkan di periksa

2021-11-13 16:54 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Jadi di atas saya ada element yang susunannya sama seperti element pada contoh pertama hanya berbeda nama class nya saja pada element di atas saya akan melakukan hal yang sama seperti pada contoh per
struturnya udah di ganti dengan kata struktur

2021-11-13 16:54 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +* kedua kita berikan aksi/event pada setiap `<div>`,tapi pada kali ini saya akan memberikan nilai bollean `true` pada setiap event nya nilai true ini memiliki arti bahwa event capture nya bernilai tr
sudah di ganti om silahkan di periksa

2021-11-13 16:54 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Hasil ketika di beri aksi/event dapat di lihat pada gift di bawah
sudah di ganti om silahkan di periksa

2021-11-13 16:54 UTC, azqilana commented on learn/DOM/008_Event_Bubbling_and_Capturing/README.md
> +Pada gift diatas sudah kita lihat pada console bahwa javascript menangkap dan menjalankan terlebih dahulu event dari pembungkus terluarnya baru setelah itu menjalankan event pada child nya.
sudah di ganti om silahkan di periksa

2021-11-13 22:51 UTC, wanrabbae approved these changes

2021-11-15 08:19 UTC, nomadkode approved these changes
LGTM 🚀

2021-11-15 08:19 UTC, merged

2021-11-15 08:51 UTC, azqilana commented
terima kasih mergenya