docs: menambahkan materi DOM Event Listener
bellshade/Javascript pull request #198
Opened 2021-11-14 06:45 UTC by hasheemi

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux / windows / macOS`

## Testing

- [x] doctesting js
- [x] lint testing eslint

## Maintainer

2021-11-14 06:58 UTC, wahyall requested changes

2021-11-14 06:58 UTC, wahyall commented on learn/DOM/006_Event_Listener/README.md
> +button.addEventListener("click", handleClick); menambahkan Event Listener Click pada element button
ini harusnya komentar kan om, kurang `//`

2021-11-14 07:02 UTC, wahyall approved these changes
Siip om, LGTM 💯

2021-11-14 07:11 UTC, wanrabbae approved these changes
LGTM om 🚀

2021-11-14 07:24 UTC, reacto11mecha approved these changes
LGTM 👍

2021-11-14 07:30 UTC, rizkyikhwan approved these changes
LGTM

2021-11-14 18:31 UTC, azqilana approved these changes

2021-11-15 03:04 UTC, dhafitf requested changes
Mungkin lebih baik ditambahkan penjelasan tentang `removeEventListener()`, karena masih masuk ke dalam materi `DOM EventListener`. Serta perhatikan penggunaan huruf kapitalnya, jika ingin mempertegas kata, cukup pertebal teksnya.

2021-11-17 09:25 UTC, reacto11mecha commented
Om @hasheemi, mau ngerjain yang web dulu kah ? Kalo iya mungkin bisa di convert jadi draft pull request yang ini

2021-11-17 10:29 UTC, hasheemi commented
> Om @hasheemi, mau ngerjain yang web dulu kah ? Kalo iya mungkin bisa di convert jadi draft pull request yang ini

Ok ok kalau besok gak bisa , saya udah ke draft , terimakasih

2021-11-18 05:37 UTC, hasheemi commented
@reacto11mecha ini kenapa ya ??

2021-11-18 05:39 UTC, reacto11mecha commented
> @reacto11mecha ini kenapa ya ??

Hirauin aja buat yang rule reviewnya,dah ada fixnya di #171

2021-11-18 05:41 UTC, hasheemi commented
ok terimakasih

2021-11-18 08:46 UTC, dhafitf approved these changes
LGTM 🚀

2021-11-18 08:51 UTC, merged