Nodelist
bellshade/Javascript pull request #228
Opened 2021-11-25 05:22 UTC by rolandopranata

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [✔] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [✔] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [✔] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [✔] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [✔] lint testing eslint

## Maintainer

2021-11-25 05:44 UTC, KimmyKx approved these changes
Udh bagus🌫

2021-11-25 09:35 UTC, reacto11mecha requested changes
Ada beberapa syntax error yang jadiin dia undefined, mungkin bisa dibaca di report [codacy](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=8468537) buat lebih lengkapnya, dan koreksi ini mungkin bisa solve problem yang ada

2021-11-25 09:35 UTC, reacto11mecha commented on learn/DOM/009_Nodelist/README.MD
> +}
Jadinya undefined dong di for of nya

```suggestion
const checkbox = document.querySelectorAll("input[type=checkbox]");

// Mengambil elemen nodelist menggunakan for of untuk memanipulasi checkbox agar terceklis untuk pertama kali
for (checkbox of check) {
  check.checked = true;
}
```

2021-11-25 09:35 UTC, reacto11mecha commented on learn/DOM/009_Nodelist/script.js
> +const check = document.querySelectorAll("input[type=checkbox]");
Mesti di ubah biar si for of nya tau variabel mana yang diambil buat looping

```suggestion
const checkbox = document.querySelectorAll("input[type=checkbox]");
```

2021-11-25 09:35 UTC, reacto11mecha commented on learn/DOM/009_Nodelist/script.js
> +  checkbox.checked = true;
Biar ngambil iterable value dari si nodelist checkbox

```suggestion
  check.checked = true;
```

2021-11-25 09:35 UTC, reacto11mecha commented on learn/DOM/009_Nodelist/script.js
> +  "Saya berkata :" + nodeList[0].innerHTML + "&" + nodeList[1].innerHTML;
Bagian yang ini diubah aja, append text node, terus jadiin template literal

```suggestion
const text = document.createTextNode(`Saya berkata : ${nodeList[0].innerHTML} & ${nodeList[1].innerHTML}`);
test.appendChild(text);
```

2021-11-25 10:25 UTC, reacto11mecha requested changes

2021-11-25 10:25 UTC, reacto11mecha commented on learn/DOM/009_Nodelist/script.js
> +}
Yang tadi salah, ini bisa jadi fix si codacy

```suggestion
for (const check of checkbox) {
  check.checked = true;
}
```

2021-11-26 09:40 UTC, reacto11mecha requested changes
Tadi dah ku benerin conflictnya, dia perlu di fetch upstream sama di pull upstream main biar up to date packagenya (coba liat #58). Kalo semisal ketemu conflict di fetch sama di pull ga bisa dan itu masalah package, jalanin `npm install` aja.

Tadi udah ku jalanin, work sih tapi kayaknya codacy perlu di tambahin `const` biar ga kebaca undefined

2021-11-26 09:40 UTC, reacto11mecha commented on learn/DOM/009_Nodelist/script.js
> +for (check of checkbox) {
```suggestion
for (const check of checkbox) {
```

2021-11-26 09:40 UTC, reacto11mecha commented on learn/DOM/009_Nodelist/README.MD
> +for (check of checkbox) {
```suggestion
for (const check of checkbox) {
```

2021-11-26 13:07 UTC, reacto11mecha approved these changes
Sip, aman aman

2021-11-26 14:48 UTC, rizkyikhwan approved these changes

2021-11-28 03:31 UTC, dhafitf approved these changes
LGTM 🚀

2021-11-28 04:53 UTC, azqilana approved these changes
LGTM

2021-11-28 12:28 UTC, merged