fix: memperbaiki typo
bellshade/Javascript pull request #232
Opened 2021-11-29 07:23 UTC by hasheemi

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [x] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux / windows / macOS`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

## Maintainer

2021-11-29 07:41 UTC, wahyall requested changes

2021-11-29 07:41 UTC, wahyall commented on learn/Basic/002_variable_datatype/README.md
> +**Keterangan**
Pakein begini om
> **Truthy**
> **Falsy**

2021-12-08 12:34 UTC, reacto11mecha commented
PR ini mau sekalian juga sama yang issue #215 kah ?

2022-01-23 07:02 UTC, closed without merging

2022-01-23 07:02 UTC, hasheemi commented
teman teman ini saya tutup , saya gabung ke pr ke 260