Menambahkan materi OOP Encapsulation
bellshade/Javascript pull request #256
Opened 2022-01-15 13:28 UTC by wahyall

Closes #222 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

2022-01-15 13:32 UTC, reacto11mecha commented
Uhhh file js nya kosong ?

2022-01-15 13:34 UTC, wahyall commented
> Uhhh file js nya kosong ?

Ehh iya deng, sorry kelupaan

2022-01-15 13:46 UTC, reacto11mecha requested changes
Jalanin prettiernya aja om buat benerin [codacynya](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=8716629)

2022-01-16 12:22 UTC, nomadkode approved these changes

2022-01-16 13:02 UTC, reacto11mecha approved these changes
Sip om di cek lokal aman, LGTM :+1:

2022-01-16 13:04 UTC, rolandopranata approved these changes

2022-01-16 22:49 UTC, merged