docs: menambahkan materi ke 2 OOP dan memberbaiki typo
bellshade/Javascript pull request #260
Opened 2022-01-23 07:00 UTC by hasheemi

Closes #221 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [x] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [x] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux / windows / macOS`

## Testing

- [ ] doctesting js
- [x] lint testing eslint

2022-01-23 07:12 UTC, wahyall requested changes

2022-01-23 07:12 UTC, wahyall commented on learn/OOP/002_Object_Property_Method/script.js
> +         this.name = name; // menggunakan property name dan age
Mungkin komentar bagian ini bisa diganti dengan
```
Mendeklarasikan property name dan age
```

2022-01-23 07:21 UTC, reacto11mecha requested changes
Nama filenya sekalian diubah dong jadi semisal `example.js` biar ga bias maka filenya.

2022-01-23 07:21 UTC, reacto11mecha commented on learn/OOP/002_Object_Property_Method/script.js
> +     }
Yang ini juga

```suggestion
     }
     
     greet() {
         console.log(`hai nama saya ${this.name} saya berumur ${this.age} tahun`)
     }
```

2022-01-23 07:21 UTC, reacto11mecha commented on learn/OOP/002_Object_Property_Method/README.md
> +     }
Method yang ini taro diluar aja jangan didalem constructornya.

```suggestion
     }
     
     greet() {
             console.log(`hai nama saya ${this.name} saya berumur ${this.age} tahun`);
     }
```

2022-01-24 06:23 UTC, reacto11mecha requested changes
Oiya lupa, di readmennya juga arahin ke filenya biar bisa langsung di klik dari dokumentasinya

2022-01-24 06:32 UTC, reacto11mecha approved these changes
Sip, dah oke bagiku, LGTM.


Request review dokumentasi @dhafitf

2022-01-24 08:45 UTC, rizkyikhwan approved these changes
LGTM

2022-01-24 12:13 UTC, wahyall approved these changes

2022-01-24 13:45 UTC, dhafitf approved these changes

2022-01-24 14:52 UTC, rolandopranata requested changes
Sedikit saran perubahan 

**Yang diubah pertama :**
- `suatu` => `sebuah`
- `Javascript` => `javascript`
- `Array juga termasuk object.` => `Perlu diingat array juga termasuk sebuah object.`

Object adalah sebuah tipe data di javascript yang bisa menyimpan banyak value atau nilai. 
Sama seperti array, yang membedakan adalah array memiliki index sedangkan object memiliki property.
Perlu diingat array juga termasuk sebuah object.

**Yang diubah kedua :**
- `14` => `20`

const person = {
    name: "salim",
    age: 20 // karena value diobjectnya 20
};

`name` dan `age` disebut property sedangkan `"salim"` dan `20` disebut value.

2022-01-24 15:35 UTC, dhafitf commented
> Sedikit saran perubahan
> 
> **Yang diubah pertama :**
> 
> * `suatu` => `sebuah`
> * `Javascript` => `javascript`
> * `Array juga termasuk object.` => `Perlu diingat array juga termasuk sebuah object.`
> 
> Object adalah sebuah tipe data di javascript yang bisa menyimpan banyak value atau nilai. Sama seperti array, yang membedakan adalah array memiliki index sedangkan object memiliki property. Perlu diingat array juga termasuk sebuah object.
> 
> **Yang diubah kedua :**
> 
> * `14` => `20`
> 
> const person = { name: "salim", age: 20 // karena value diobjectnya 20 };
> 
> `name` dan `age` disebut property sedangkan `"salim"` dan `20` disebut value.

Oke terima kasih. Tadi saya kelewatan di value yang `14`.
Untuk yang `Javascript`, saya rasa tidak masalah, karena jika saya melihat di sumber-sumber lain, penulisannya justru menggunakan `JavaScript`.

2022-01-24 15:38 UTC, rolandopranata approved these changes
Ok udah aman...LGTM🚀

2022-01-24 15:46 UTC, dhafitf approved these changes

2022-01-24 15:53 UTC, KimmyKx approved these changes

2022-01-24 18:03 UTC, merged