docs: menambahkan operator double bang
bellshade/Javascript pull request #261
Opened 2022-01-24 13:57 UTC by KimmyKx

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [x] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im using):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

2022-01-24 14:13 UTC, wahyall approved these changes
LGTM 💯

2022-01-24 14:25 UTC, dhafitf approved these changes

2022-01-24 14:57 UTC, rolandopranata requested changes
Kayaknya lebih better kalo `adalahnya` diilangin :

Nullish coalescing operator merupakan logical operator yang mengembalikan right-hand value jika left-hand bernilai `null` atau `undefined`.

2022-01-24 15:58 UTC, rolandopranata approved these changes

2022-01-24 18:08 UTC, reacto11mecha requested changes

2022-01-24 18:08 UTC, reacto11mecha commented on learn/Basic/003_operator/doubleBangOperator.js
> +const notDefined = undefined;
Ditambahin pengaturan buat matiin eslint yang ga nerima `undefined`, buat benerin issue si [codacynya](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=8760963).

```suggestion
/* eslint-disable-next-line */
const notDefined = undefined;
```

2022-01-25 10:50 UTC, reacto11mecha approved these changes
Sip, LGTM :+1:

2022-01-25 10:51 UTC, merged