Menambahkan materi Functional Programming
bellshade/Javascript pull request #274
Opened 2022-02-07 03:59 UTC by Fakhri1999

Closes #269 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [x] doctesting js
- [x] lint testing eslint

2022-02-07 05:48 UTC, slowy07 approved these changes
LGTM, request review and merge @reacto11mecha

2022-02-07 06:46 UTC, reacto11mecha requested changes
Sebelumnya makasih udah effort buat materi sebanyak ini, sampe 5 materi 1 PR doang.

Untuk review yang di bawah bawah itu buat style kodingan biar lebih rapih di baca. Terus nama file js nya diganti jadi `example.js` aja biar ga bingung buat yang baca. Terus di file `README.md` nya juga dikasih arahan ke file `example.js` nya

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/001_Introduction/index.js
> +console.log(salam + nama); // "Halo Bellshade"
```suggestion
const salam = "Halo ";

console.log(salam + nama); // "Halo Bellshade"
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/001_Introduction/README.md
> +console.log(salam + nama); // "Halo Bellshade"
```suggestion
const salam = "Halo ";

console.log(salam + nama); // "Halo Bellshade"
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/002_First_Class_Object/README.md
> +console.log(convert(cmToM, nilaiAwal)); // 1
```suggestion
const convert = (fn, length) => fn(length);

const nilaiAwal = 100;

console.log(convert(cmToM, nilaiAwal)); // 1
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/002_First_Class_Object/README.md
> +const hello = helloFunc();
```suggestion
};

const hello = helloFunc();
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/002_First_Class_Object/index.js
> +console.log(convert(cmToM, nilaiAwal)); // 1
```suggestion
const convert = (fn, length) => fn(length);

const nilaiAwal = 100;

console.log(convert(cmToM, nilaiAwal)); // 1
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/002_First_Class_Object/index.js
> +const hello = helloFunc();
```suggestion
};

const hello = helloFunc();
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/003_Pure_Function/README.md
> +console.log(salam("Bellshade")); // Halo Bellshade
```suggestion
};

console.log(salam("Bellshade")); // Halo Bellshade
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/003_Pure_Function/README.md
> +console.log(salam("Bellshade")); // Pagi Bellshade
```suggestion
let sapaan = "Halo";

const salam = (nama) => {
  return `${sapaan} ${nama}`;
};

console.log(salam("Bellshade")); // Halo Bellshade

sapaan = "Pagi";
console.log(salam("Bellshade")); // Pagi Bellshade
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/003_Pure_Function/index.js
> +console.log(salam("Bellshade")); // Halo Bellshade
```suggestion
};

console.log(salam("Bellshade")); // Halo Bellshade
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/003_Pure_Function/index.js
> +console.log(salamBaru("Bellshade")); // Pagi Bellshade
```suggestion
let sapaan = "Halo";

const salamBaru = (nama) => {
  return `${sapaan} ${nama}`;
};

console.log(salamBaru("Bellshade")); // Halo Bellshade

sapaan = "Pagi";
console.log(salamBaru("Bellshade")); // Pagi Bellshade
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/004_High_Order_Function/README.md
> +console.log(arr2); // [2, 4, 6, 8, 10]
```suggestion
const arr2 = [];

for (let i = 0; i < arr1.length; i++) {
  arr2.push(arr1[i] * 2);
}

console.log(arr2); // [2, 4, 6, 8, 10]
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/004_High_Order_Function/README.md
> +console.log(arr2); // [2, 4, 6, 8, 10]
```suggestion
});

console.log(arr2); // [2, 4, 6, 8, 10]
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/004_High_Order_Function/README.md
> +console.log(lakukanOperasi(5, kali2)); // 10
```suggestion
const lakukanOperasi = (num, fn) => fn(num);

console.log(lakukanOperasi(5, kali2)); // 10
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/004_High_Order_Function/index.js
> +console.log(arr2);
```suggestion
const arr2 = [];

for (let i = 0; i < arr1.length; i++) {
  arr2.push(arr1[i] * 2);
}

console.log(arr2);
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/004_High_Order_Function/index.js
> +console.log(arrB); // [2, 4, 6, 8, 10]
```suggestion
});

console.log(arrB); // [2, 4, 6, 8, 10]
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/004_High_Order_Function/index.js
> +console.log(lakukanOperasi(5, kali2)); // 10
```suggestion
const lakukanOperasi = (num, fn) => fn(num);

console.log(lakukanOperasi(5, kali2)); // 10
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/005_Composition/README.md
> +console.log(ubahJadiHurufBesar(ubahFormatNama(namaOrang)));
```suggestion
const namaOrang = "bellshade_javascript";

console.log(ubahJadiHurufBesar(ubahFormatNama(namaOrang)));
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/005_Composition/README.md
> +console.log(daftarPenggunaTerpilih); // [{ name: "Sinta", umur: 17, jenisKelamin: "perempuan" }]
```suggestion
  .filter(apakahPerempuan);
  
console.log(daftarPenggunaTerpilih); // [{ name: "Sinta", umur: 17, jenisKelamin: "perempuan" }]
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/005_Composition/index.js
> +console.log(ubahJadiHurufBesar(ubahFormatNama(namaOrang)));
```suggestion
const namaOrang = "bellshade_javascript";

console.log(ubahJadiHurufBesar(ubahFormatNama(namaOrang)));
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/005_Composition/index.js
> +console.log(daftarPenggunaTerpilih); // [{ name: "Sinta", umur: 17, jenisKelamin: "perempuan" }]
```suggestion
  .filter(apakahPerempuan);
  
console.log(daftarPenggunaTerpilih); // [{ name: "Sinta", umur: 17, jenisKelamin: "perempuan" }]
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/006_Immutability/README.md
> +console.log(mobilBaru); // { model: "Honda", tahun: 2020 }
```suggestion
};

console.log(mobil); // { model: "Tesla", tahun: 2020 }

mobil.model = "Honda";
console.log(mobilBaru); // { model: "Honda", tahun: 2020 }
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/006_Immutability/README.md
> +console.log(mobil); // { model: "Tesla", tahun: 2020 }
```suggestion
const mobilBaru = { ...mobil, model: "Honda" };

console.log(mobil); // { model: "Tesla", tahun: 2020 }
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/006_Immutability/index.js
> +console.log(mobil); // { model: "Honda", tahun: 2020 }
```suggestion
};

console.log(mobil); // { model: "Tesla", tahun: 2020 }

mobil.model = "Honda";
console.log(mobil); // { model: "Honda", tahun: 2020 }
```

2022-02-07 06:46 UTC, reacto11mecha commented on learn/FP/006_Immutability/index.js
> +console.log(mobilImmutable); // { model: "Tesla", tahun: 2020 }
```suggestion
const mobilBaru = { ...mobilImmutable, model: "Honda" };

console.log(mobilImmutable); // { model: "Tesla", tahun: 2020 }
```

2022-02-07 14:36 UTC, slowy07 approved these changes

2022-02-07 22:10 UTC, KimmyKx commented on learn/FP/001_Introduction/README.md
> +Salah satu paradigma pemrograman yang bisa dilakuakan pada Javascript adalah [Functional Programming](https://en.wikipedia.org/wiki/Functional_programming).
```suggestion
Salah satu paradigma pemrograman yang bisa dilakukan pada Javascript adalah [Functional Programming](https://en.wikipedia.org/wiki/Functional_programming).
```

2022-02-07 22:13 UTC, KimmyKx commented on learn/FP/002_First_Class_Object/README.md
> +> **Informasi**: Untuk kedepannya, penulisan function dalam materi ini akan menggunakan [arrow function](../../ES6/003_arrow_function) dikarenekan pada FP, tidak memerlukan _keyword_ `this` sesuai ko
```suggestion
> **Informasi**: Untuk kedepannya, penulisan function dalam materi ini akan menggunakan [arrow function](../../ES6/003_arrow_function) dikarenakan pada FP, tidak memerlukan _keyword_ `this` sesuai konsep [Pure Function](../003_Pure_Function).
```

2022-02-07 22:16 UTC, KimmyKx commented on learn/FP/002_First_Class_Object/example.js
> +console.log(hello()); // Hello!
Outputnya ini undefined, coba di cek ulang codenya

2022-02-08 01:53 UTC, Fakhri1999 commented on learn/FP/002_First_Class_Object/example.js
> +console.log(hello()); // Hello!
oh iya lupa gk ngereturn apa2

2022-02-08 03:15 UTC, nomadkode approved these changes

2022-02-08 03:20 UTC, KimmyKx approved these changes
LGTM👌

2022-02-08 05:30 UTC, rizkyikhwan approved these changes

2022-02-08 10:04 UTC, reacto11mecha requested changes
Satu perubahan terakhir sebelum di merge, nama folder `FP` nya di ubah jadi `Functional`

2022-02-08 11:03 UTC, Fakhri1999 commented
done @reacto11mecha

2022-02-08 11:15 UTC, reacto11mecha approved these changes
Sip, terimakasih atas kontribusinya ya 👍

2022-02-08 11:15 UTC, merged