:feat menambahkan sistem ganti port pada webserver
bellshade/Javascript pull request #292
Opened 2022-03-10 15:52 UTC by LintangDev

Closes 

## Deskripsi (Description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

2022-03-11 00:06 UTC, dhafitf requested changes

2022-03-11 00:06 UTC, dhafitf commented on package.json
> +  "main": "server/app.js",
Ada [perubahan yang sama](https://github.com/bellshade/Javascript/pull/290/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L5-R5) pada file `package.json` di #290. Saya rasa itu akan menimbulkan konflik. Mohon untuk memilih salah satu Pull Request yang akan digunakan untuk merubah file `package.json` ini.

2022-03-11 04:19 UTC, reacto11mecha requested changes
Konfigurasinya jangan pake file json, pake file `.env` aja. Takutnya kalo ada file `port.json` itu nanti malah masuk ke commitnya. Jangan lupa install [dotenv](https://npm.im/dotenv) juga sekalian nanti di tambahin di `server/app.js`.

Sekalian di file `.gitignore` nya di tambahin file `.env` biar ga ke track git nya

2022-03-11 04:19 UTC, reacto11mecha commented on server/app.js
> +const port = require("../port.json").port;
Dibikin dia ada default portnya ke `3000`

```suggestion
const port = process.env.PORT || 3000;
```

2022-03-11 04:19 UTC, reacto11mecha commented on port.json
> +}
File ini dihapus aja atau di rename jadi `.env.sample` dan isinya nanti jadi begini

```suggestion
PORT=
```

2022-03-11 04:19 UTC, reacto11mecha commented on learn/Basic/README.md
> +
Harusnya ini di pindahin ke readme rootnya, sebenernya kamu bsia ngeclose issue #215 tapi coba ngomong dulu sama @hasheemi, biar ga salah paham. Soalnya ini issuenya dah lama tapi kamu udah ngerjain duluan.

Nanti di rootnya tambahin cara instalasi sama ini sebenernya kurang tepat sih, nanti ada yang review kok

2022-03-11 06:09 UTC, LintangDev commented on learn/Basic/README.md
> +
instalasi apa btw?

2022-03-11 07:08 UTC, reacto11mecha commented on learn/Basic/README.md
> +
Ya instalasi modulemya, `npm install`

2022-03-18 12:14 UTC, reacto11mecha commented
Progressnya udah sampe mana @LintangDev ?

2022-03-20 10:11 UTC, reacto11mecha requested changes
Untuk fungsionalitas, udah oke dan jalan pake `node .` maupun `npm start`. Sisanya tinggal penulisan aja yang kurang

2022-03-20 10:11 UTC, reacto11mecha commented on server/app.js
> +require('dotenv').config()
Ada issue [codacy](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=9041083), harus pake doublequote sama semicolon

```suggestion
require("dotenv").config();
```

2022-03-20 10:18 UTC, LintangDev commented on server/app.js
> +require('dotenv').config()
> Ada issue [codacy](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=9041083), harus pake doublequote sama semicolon

sudah di edit dan di push silakan di cek kembali, terimakasih

2022-03-20 10:33 UTC, reacto11mecha approved these changes
Sip, LGTM 👍

2022-03-20 12:35 UTC, reacto11mecha requested changes

2022-03-20 12:35 UTC, reacto11mecha commented on package.json
> +    "dotenv": "^16.0.0",
Oiya kelupaan, jangan lupa di pin dependensinya

```suggestion
    "dotenv": "16.0.0",
```

2022-03-21 06:25 UTC, reacto11mecha approved these changes

2022-03-21 06:26 UTC, nomadkode approved these changes

2022-03-21 06:33 UTC, merged