fix: memperbaiki bug tampilan pada code highlight di readme
bellshade/Javascript pull request #307
Opened 2022-04-11 17:52 UTC by fahmiidris-labs

Closes #250 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

2022-04-12 12:46 UTC, reacto11mecha requested changes
Makasih udah mau berkontribusi ke bellshade repositori javascript, pas di coba udah aman di local, tapi ada issue codacy sedikit. 

Oiya, karena nanti viewer ini jadi lebih universal, fix nya nanti bakalan pindah ke [`@bellshade/ningali`](https://github.com/bellshade/bellshade-monorepo/tree/main/packages/ningali). Karena masnya udah buat fixnya, minta tolong juga dong kontribusi kesana, biar kecatet juga namanya disitu

2022-04-12 12:46 UTC, reacto11mecha commented on server/public/css/nodeViewer.css
> +}
Ada minor error dari [codacy](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=9232556) yang mengharuskan ada new line di akhir file, dan juga ini dipake disebelah mana ya css nya ?

```suggestion
}

```

2022-04-12 13:38 UTC, reacto11mecha commented
Uhh, masih belum ketambah new linenya, mungkin karena settingan code editornya, coba di jalanin prettiernya

```sh
npm run prettier
```

2022-04-12 13:58 UTC, reacto11mecha commented
Di reopen aja kalo kepencet mas

2022-04-12 14:02 UTC, fahmiidris-labs commented
> Di reopen aja kalo kepencet mas

Mas, si new line nya itu selalu kehapus pas di push. padahal di local nya ada.

2022-04-12 15:19 UTC, reacto11mecha approved these changes
Sip, LGTM 👍 , kalo bisa contrib di repositori monorepo yah buat masukin fix ini ke sana ya

2022-04-13 06:54 UTC, nomadkode approved these changes

2022-04-13 10:30 UTC, merged