docs: menambahkan cara setup ui server
bellshade/Javascript pull request #308
Opened 2022-04-17 06:46 UTC by hasheemi

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux / windows / macOS`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

2022-04-17 12:44 UTC, nomadkode approved these changes

2022-04-17 20:59 UTC, reacto11mecha requested changes
Tata caranya dah bener, tinggal penulisannya aja yang perlu dibenerin dikit

2022-04-17 20:59 UTC, reacto11mecha commented on README.md
> +- Nodejs
```suggestion
- Git
- Node.js
```

2022-04-17 20:59 UTC, reacto11mecha commented on README.md
> +#### install git
```suggestion
#### Instalasi git
```

2022-04-17 20:59 UTC, reacto11mecha commented on README.md
> +jika belum kalian bisa klik dan ikuti video dibawah ini untuk menginstall semua program yang dibutuhkan
```suggestion
Jika belum kalian bisa klik dan ikuti video dibawah ini untuk menginstall semua program yang dibutuhkan
```

2022-04-17 20:59 UTC, reacto11mecha commented on README.md
> +#### install Nodejs dan NPM
```suggestion
#### Instalasi Node.js dan NPM
```

2022-04-17 20:59 UTC, reacto11mecha commented on README.md
> +lalu jalankan kembali UI Server nya
```suggestion
Lalu jalankan kembali UI Server nya.
```

2022-04-18 05:35 UTC, dhafitf requested changes

2022-04-18 05:35 UTC, dhafitf commented on README.md
> +Dengan UI Server kalian bisa belajar bahasa pemrograman Javascript dan langsung mempraktekan topik yang sudah kalian pelajari, Bagaimana caranya ?
```suggestion
Dengan UI Server, kalian bisa belajar bahasa pemrograman Javascript dan langsung mempraktikkan topik yang sudah kalian pelajari, Bagaimana caranya?
```

2022-04-18 05:35 UTC, dhafitf commented on README.md
> +Jika sudah terinstall kalian bisa ikuti langkah langkah berikut ini
```suggestion
Jika sudah terinstall, kalian bisa ikuti langkah langkah berikut ini
```

2022-04-18 05:35 UTC, dhafitf commented on README.md
> +- Pindahkan ke direktori hasil _clone_ nya Lalu jalankan perintah
```suggestion
- Pindahkan ke direktori hasil _clone_ nya, lalu jalankan perintah
```

2022-05-07 07:55 UTC, reacto11mecha commented on README.md
> +jika belum kalian bisa klik dan ikuti video dibawah ini untuk menginstall semua program yang dibutuhkan
Yang ini belum @hasheemi ?

2022-05-07 11:23 UTC, reacto11mecha commented
Uhh, belum di push kah?

2022-05-08 01:21 UTC, hasheemi commented on README.md
> +jika belum kalian bisa klik dan ikuti video dibawah ini untuk menginstall semua program yang dibutuhkan
wkwkw kelewatan
bentar zra

2022-05-08 01:24 UTC, hasheemi commented
oke dah

2022-05-10 01:43 UTC, reacto11mecha requested changes
Ada yang kelewat dua @hasheemi, coba dibenerin lagi

2022-05-10 01:43 UTC, reacto11mecha commented on README.md
> +#### instalasi git
```suggestion
#### Instalasi git
```

2022-05-10 01:43 UTC, reacto11mecha commented on README.md
> +#### instalasi Node.js dan NPM
```suggestion
#### Instalasi Node.js dan NPM
```

2022-05-10 01:45 UTC, reacto11mecha commented
> done ngga?

belum om

2022-05-11 06:35 UTC, reacto11mecha approved these changes
Dah aman, langsung di merge aja. Udah sesuai juga sama reviewnya om dhafit

2022-05-11 06:37 UTC, merged