add: menambahkan materi tentang webrtc
bellshade/Javascript pull request #323
Opened 2022-06-08 10:57 UTC by Febri-i

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux`

## Testing

- [x] doctesting js
- [x] lint testing eslint

2022-06-08 11:56 UTC, KimmyKx commented
LGTM tapi codacy boleh di fix dulu ka bisa cek [disini](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=9577388) yang perlu diperbaiki

2022-06-09 00:55 UTC, reacto11mecha requested changes

2022-06-09 00:55 UTC, reacto11mecha commented on learn/WebApi/WebRTC/WebRTCVideoCall_Example/client/asset/index.js
> +  if (peer.id !=== data.id) {
Operatornya ada yang salah

```suggestion
  if (peer.id !== data.id) {
```

2022-06-09 09:35 UTC, reacto11mecha commented
Masih ada beberapa pesan commit yang belum sesuai, seharusnya ditambahin prefix `fix:` supaya pesan commit nya valid. Kaerna kalo di liat kamu ngubah langsung di gthub, pastiin apa yang kamu lakuin di github sama kayak yang di local punyamu, di `pull` dulu perubahannya di branch yag sama. Pastiin udah ad di branch `webrtc`.

```sh
git pull origin webrtc
```
Baru abis itu ngerubah pesan commitnya.
Jadi ada 4 commit yang salah, ada di [`b035420`](https://github.com/bellshade/Javascript/pull/323/commits/b0354209bea67d37bf6f7ff5348745b1e4104799), [`3acd631`](https://github.com/bellshade/Javascript/pull/323/commits/3acd631c16fb35f8c1c81bc1ab66da86792ea7d2), [`5117bc6`](https://github.com/bellshade/Javascript/pull/323/commits/5117bc6a7f39567595b44eb6a86d4e24cb4e01a5), sama [`d5a11b9`](https://github.com/bellshade/Javascript/pull/323/commits/d5a11b95577b448be4de6f2147bade75bb79a4e1).

Buat ngubah pesan commitnya yang paling gampang dulu yaitu paling terbaru. Caranya di `amend`.

> Catatan: setelah `fix:` dia harus huruf kecil, karena aturan commitnya memang begitu, contohnya ada di bawah ini

```bash
git commit --amend -m "fix: update index.js"
git push -f
```

Terus langkah selanjutnya ngubah 3 commit sisanya, caranya hampir sama tapi ada tambahan sedikit. Kamu perlu rebase interactive buat ngubah pesan commit sisanya.

Perintah yang harus dijalankan kayak begini, semisal mau ngubah `3acd631`, bisa kayak begini. Pastiin formatnya harus `'<nomor commit>^'`.
```bash
git rebase --interactive '3acd631^'
```

Nanti bakalan ada tulisan

```
pick 3acd631
```

Ubah tulisan `pick` jadi `edit`, abis itu save. Setelahnya baru bisa di amend kayak sebelumnya dan rebase continue. Pastiin pesan commitnya sama kayak nomor commitnya.

```bash
git commit --amend -m "fix: <pesan commitnya disini>"
git rebase --continue
```

Abis itu push force deh
```bash
git push -f
```

Lakuin ini buat commit [`5117bc6`](https://github.com/bellshade/Javascript/pull/323/commits/5117bc6a7f39567595b44eb6a86d4e24cb4e01a5) sama [`d5a11b9`](https://github.com/bellshade/Javascript/pull/323/commits/d5a11b95577b448be4de6f2147bade75bb79a4e1).

2022-06-09 11:42 UTC, reacto11mecha commented
Di close ya, sesuai informasi di discord

2022-06-09 11:42 UTC, closed without merging