add: menambahkan materi tentang webrtc
bellshade/Javascript pull request #324
Opened 2022-06-09 11:59 UTC by Febri-i

## Deskripsi (Description)

-   [ ] saya menambahkan algoritma terbaru
-   [ ] saya memperbaiki algoritma yang sudah ada
-   [x] saya menambahkan materi/sub materi belajar
-   [ ] saya memperbaiki materi/sub materi belajar
-   [x] saya menambah dokumentasi
-   [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

-   [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
-   [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
-   [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

-   `os` = `linux`

## Testing

-   [x] doctesting js
-   [x] lint testing eslint

2022-06-09 14:09 UTC, reacto11mecha requested changes
Makasih sebelumnya udah kontribusi materi web rtc, udah di coba di local dan jalan. Disini ada beberapa koreksi sedikut terkait penggunaan `addEventListener` sama mengeliminasi pemanggilan elemen berulang kali. Soalnya di [`mdn`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection?retiredLocale=id#events) itu udah dijelasin kalo `RTCPeerConnection` bisa pake `addEventListener` karena lebih rapih daripada pake `oneventname`.

Terus juga ada beberapa yang harus di ubah biar struktur folder sama user lebih enak buat yang lagi belajar. Folder `WebRTCVideoCall_Example` itu ga usah dibikin beda folder, samain aja isi filenya di `learn/WebApi/WebRTC`. Untuk package `ws` install aja di root projectnya biar nanti ga usah install lagi dependensi didalem foldernya.

Di `package.json` root repositori ini, tambahin script baru yang namanya `example:webrtc`.

```json
{
    "scripts": {
       // ...
       "example:webrtc": "node learn/WebApi/WebRTC/server/index.js"
    }
}
```

Terus di readmenya dijelasin contoh penggunaannya, kayak apa aja libary yang dibutuhin (kan ada `ws`), Web API apa aja yang dipake, sama gimana cara penggunaannya (`npm run example:webrtc`) secara rinci.

Oiya, untuk komentar di tiap file js nya diubah jadi huruf yang normal semisal kayak `BIAR GAK NULIS 'type: ' BERKALI KALI` itu bisa jadi `Biar gak nulis 'type:' berkali-kali` supaya lebih enak dibaca sama yang baca kodenya.

2022-06-09 23:00 UTC, Febri-i commented
Terimakasih atas reviewnya. Akan saya kerjakan hari minggu karena hari ini sampai sabtu saya ada kegiatan.

2022-06-09 23:18 UTC, reacto11mecha commented
> Terimakasih atas reviewnya. Akan saya kerjakan hari minggu karena hari ini sampai sabtu saya ada kegiatan.

Okey gapapa

2022-06-24 23:44 UTC, reacto11mecha commented on learn/WebApi/WebRTC/client/datachannel.html
> +			).innerHTML += `<span class="textChat">from ${calling}:\n${message.data.toString()}</span>`;
@Febri-i ini kayaknya harus dibuat createElement biar warning ini ilang

2022-06-24 23:44 UTC, reacto11mecha commented on learn/WebApi/WebRTC/client/datachannel.html
> +			).innerHTML += `<span class="textChat">you send:\n${message}</span>`;
@Febri-i yang ini juga, terus jangan lupa jalanin prettiernya

2022-07-11 05:27 UTC, closed without merging