add: menambahkan algoritma baru
bellshade/Javascript pull request #329
Opened 2022-06-27 13:28 UTC by mariadhari6

Closes 

## Deskripsi (Description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux`

## Testing

- [x] doctesting js
- [x] lint testing eslint

2022-06-29 12:41 UTC, reacto11mecha requested changes
Sebelumnya terimakasih sudah berkontribusi ke bellshade repositori js. Untuk kodenya secara kegunaan udah bagus tetapi ada beberapa hal yang harus diubah biar bisa di merge.

Sebelum nerapin saran ini, nama filenya di ubah dulu jadi `isSortedChecking` soalnya kalo `shorted` artinya beda sama yang dimaksud dari kode kamu, kalau diliat ini maksud dari kodenya array itu dari atas ke bawah atau sebaliknya atau bukan.

Terus pindahin filenya ke folder `/algorithm/validation`, soalnya ini ngevalidasi isi array kayak gimana isinya.

Untuk masalah algoritmanya, coba ditambahin arraynya itu di cek dulu ada isinya atau nggak, kira kira snippetnya kayak begini. Tambahinnya di ` isAscending` sama di `isDescending`, kalo kosong langsung return `false` aja. Taro sebelum looping.

```js
if (!arr || arr.length < 1) return false;
```

2022-06-29 12:41 UTC, reacto11mecha commented on algorithm/other/isShortedChecking.js
> +function isShortedAndHow(arr) {
Yang ini juga dikasih jarak, terus nama `shorted` harusnya jadi `sorted` soalnya artinya jadi `dipendekan`

```suggestion
}

function isSortedAndHow(arr) {
```

2022-06-29 18:27 UTC, mariadhari6 commented
> Sebelumnya terimakasih sudah berkontribusi ke bellshade repositori js. Untuk kodenya secara kegunaan udah bagus tetapi ada beberapa hal yang harus diubah biar bisa di merge.
> 
> Sebelum nerapin saran ini, nama filenya di ubah dulu jadi `isSortedChecking` soalnya kalo `shorted` artinya beda sama yang dimaksud dari kode kamu, kalau diliat ini maksud dari kodenya array itu dari atas ke bawah atau sebaliknya atau bukan.
> 
> Terus pindahin filenya ke folder `/algorithm/validation`, soalnya ini ngevalidasi isi array kayak gimana isinya.
> 
> Untuk masalah algoritmanya, coba ditambahin arraynya itu di cek dulu ada isinya atau nggak, kira kira snippetnya kayak begini. Tambahinnya di ` isAscending` sama di `isDescending`, kalo kosong langsung return `false` aja. Taro sebelum looping.
> 
> ```js
> if (!arr || arr.length < 1) return false;
> ```



> Sebelumnya terimakasih sudah berkontribusi ke bellshade repositori js. Untuk kodenya secara kegunaan udah bagus tetapi ada beberapa hal yang harus diubah biar bisa di merge.
> 
> Sebelum nerapin saran ini, nama filenya di ubah dulu jadi `isSortedChecking` soalnya kalo `shorted` artinya beda sama yang dimaksud dari kode kamu, kalau diliat ini maksud dari kodenya array itu dari atas ke bawah atau sebaliknya atau bukan.
> 
> Terus pindahin filenya ke folder `/algorithm/validation`, soalnya ini ngevalidasi isi array kayak gimana isinya.
> 
> Untuk masalah algoritmanya, coba ditambahin arraynya itu di cek dulu ada isinya atau nggak, kira kira snippetnya kayak begini. Tambahinnya di ` isAscending` sama di `isDescending`, kalo kosong langsung return `false` aja. Taro sebelum looping.
> 
> ```js
> if (!arr || arr.length < 1) return false;
> ```

Baik kak, untuk memindahkan file berarti apakah harus melakukan pull request ulang?

2022-06-30 11:35 UTC, reacto11mecha commented
> > Sebelumnya terimakasih sudah berkontribusi ke bellshade repositori js. Untuk kodenya secara kegunaan udah bagus tetapi ada beberapa hal yang harus diubah biar bisa di merge.
> > Sebelum nerapin saran ini, nama filenya di ubah dulu jadi `isSortedChecking` soalnya kalo `shorted` artinya beda sama yang dimaksud dari kode kamu, kalau diliat ini maksud dari kodenya array itu dari atas ke bawah atau sebaliknya atau bukan.
> > Terus pindahin filenya ke folder `/algorithm/validation`, soalnya ini ngevalidasi isi array kayak gimana isinya.
> > Untuk masalah algoritmanya, coba ditambahin arraynya itu di cek dulu ada isinya atau nggak, kira kira snippetnya kayak begini. Tambahinnya di ` isAscending` sama di `isDescending`, kalo kosong langsung return `false` aja. Taro sebelum looping.
> > ```js
> > if (!arr || arr.length < 1) return false;
> > ```
> 
> > Sebelumnya terimakasih sudah berkontribusi ke bellshade repositori js. Untuk kodenya secara kegunaan udah bagus tetapi ada beberapa hal yang harus diubah biar bisa di merge.
> > Sebelum nerapin saran ini, nama filenya di ubah dulu jadi `isSortedChecking` soalnya kalo `shorted` artinya beda sama yang dimaksud dari kode kamu, kalau diliat ini maksud dari kodenya array itu dari atas ke bawah atau sebaliknya atau bukan.
> > Terus pindahin filenya ke folder `/algorithm/validation`, soalnya ini ngevalidasi isi array kayak gimana isinya.
> > Untuk masalah algoritmanya, coba ditambahin arraynya itu di cek dulu ada isinya atau nggak, kira kira snippetnya kayak begini. Tambahinnya di ` isAscending` sama di `isDescending`, kalo kosong langsung return `false` aja. Taro sebelum looping.
> > ```js
> > if (!arr || arr.length < 1) return false;
> > ```
> 
> Baik kak, untuk memindahkan file berarti apakah harus melakukan pull request ulang?

Yaa, ga usah sih, tinggal dipindahin aja

2022-06-30 11:55 UTC, reacto11mecha commented
Sebenernya kalo rename sama mau ngubah bagusnya di local, soalnya nanti pesan commitnya berantakan (bisa cek [disini] pesan commit yang salah dimana aja) dan beberapa commit harusnya dikasih prefix commit kayak `fix: ` 
 sebelum pesan commit yang sebenernya. Coba dibaca lagi [panduan kontribusinya](https://github.com/bellshade/Javascript/blob/main/CONTRIBUTING.md) lagi.

Ada dua pilihan, mau ngubah pesan commit atau mau di fork ulang, soalnya agak ribet kalo mau ngubah pesan commit satu satu. Kalau mau liat panduannya gimana bisa liat https://github.com/bellshade/Javascript/pull/323#issuecomment-1150897606.

2022-06-30 16:18 UTC, closed without merging