feat: add geolocation status
bellshade/Javascript pull request #333
Opened 2022-07-27 18:41 UTC by arcetros

Closes 

## Deskripsi (Description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `windows` = `linux / windows / macOS`

## Testing

- [ ] doctesting js
- [x] lint testing eslint

2022-07-27 20:57 UTC, reacto11mecha requested changes
Sebelumnya terimakasih sudah membuat pull request ke bellshade repositori js, masih ada beberapa yang salah, tapi bisa di benerin. Cek beberapa yang salah di [codacy](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=9875017)

2022-07-27 20:57 UTC, reacto11mecha commented on learn/WebApi/GeoLocation/geolocation.js
> +  navStatus.innerHTML = `ERROR: ${err.message} (${err.code})`;
Buat benerin codacynya, coba diganti innerText

```suggestion
  navStatus.innerText = `ERROR: ${err.message} (${err.code})`;
```

2022-07-28 20:51 UTC, reacto11mecha requested changes
Di test di local dah aman

![2022-07-29_03-49](https://user-images.githubusercontent.com/48118327/181634924-0e36112c-e06c-4368-9cae-a961af3264df.png)

Oiya, sekalian juga di update yang ada di README nya geolocation, biar langsung sekalian. Tinggal tambahin penjelasan callback pada saat errornya

2022-07-29 04:08 UTC, arcetros commented
> Oiya, sekalian juga di update yang ada di README nya geolocation, biar langsung sekalian. Tinggal tambahin penjelasan callback pada saat errornya

Hehe, kelupaan saya gan

2022-07-29 06:04 UTC, reacto11mecha approved these changes
Okeh, LGTM!

2022-07-31 15:30 UTC, rizkyikhwan approved these changes

2022-08-01 10:35 UTC, hasheemi approved these changes

2022-08-01 17:22 UTC, merged