feat: menambahkan fungsi untuk melarang mem-paste
bellshade/Javascript pull request #338
Opened 2022-09-15 16:33 UTC by mushlih-almubarak

Closes 

## Deskripsi (Description)
Fungsi ini berguna untuk mencegah agar user tidak bisa mempaste di inputan di form website kita.

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [x] lint testing eslint

2022-09-16 06:11 UTC, hasheemi requested changes
Mungkin bisa ditambahkan contoh code penerapan algoritma prevent paste

2022-09-16 08:19 UTC, mushlih-almubarak commented
Oke, sudah saya tambahkan contoh penerapannya

2022-09-17 06:07 UTC, reacto11mecha requested changes
Kayaknya ini perlu dibikin contoh pake UI server yang kita punya, pas di coba sesuai contoh bikin sendiri bisa, cuman kalo kode doang kurang bagus penyampaiannya, harus ada contoh langsung.

Di folder `algorithm`, buat folder baru lagi namanaya `WebRelated`, nah didalemnya lagi bikin folder lagi namanya `preventPaste`. 

Jadi pathnya ada di `/algorithm/WebRelated/preventPaste`. Didalemnya bikin dua file, file `index.html` sama `prevent.js`. Bikin inputnya sama keterangan dikit suruh paste sesuatu di htmlnya, terus bikin listenernya buat ngelisten input pake `addEventListener`.

2022-09-17 06:15 UTC, mushlih-almubarak commented
Siap mas, tapi apakah saya harus pakai `addEventListener` dan tidak boleh pakai atribut `onpaste="..."` ?

2022-09-17 10:40 UTC, reacto11mecha commented
> Siap mas, tapi apakah saya harus pakai `addEventListener` dan tidak boleh pakai atribut `onpaste="..."` ?

Ga bagus kalo pake `onevent` secara best practice, tapi tetep sama kok hasilnya.

2022-09-18 16:02 UTC, mushlih-almubarak commented
> Kayaknya ini perlu dibikin contoh pake UI server yang kita punya, pas di coba sesuai contoh bikin sendiri bisa, cuman kalo kode doang kurang bagus penyampaiannya, harus ada contoh langsung.
> 
> Di folder `algorithm`, buat folder baru lagi namanaya `WebRelated`, nah didalemnya lagi bikin folder lagi namanya `preventPaste`.
> 
> Jadi pathnya ada di `/algorithm/WebRelated/preventPaste`. Didalemnya bikin dua file, file `index.html` sama `prevent.js`. Bikin inputnya sama keterangan dikit suruh paste sesuatu di htmlnya, terus bikin listenernya buat ngelisten input pake `addEventListener`.

Oke, saya sudah lakukan

2022-09-19 20:41 UTC, reacto11mecha commented
Hmm commit messagenya ada yang ga valid, perlu dibenerin dulu. Salahnya ada di `Menghapus file preventPaste.js`.

Caranya direbase dulu ke commit [`b932127`](https://github.com/bellshade/Javascript/pull/338/commits/b93212751931584f623c305fb45b6514d07d1a4a), caranya
```sh
git rebase --interactive 'b932127^'
```

Nanti akan kebuka editor default gitnya, terus edit baris yang ada `b932127` yang awalnya `pick` jadi `edit`.

Kalo udah di save baru di ubah pesan commitnya.
```sh
git commit --all --amend --no-edit -m "fix: menghapus file preventPaste.js"
```

Setelahnya di rebase continue biar balik ke commit yang paling baru
```sh
git rebase --continue
```

Nah setelahnya baru di push, tapi mesti di `force`.
```sh
git push --force
```

2022-09-20 15:01 UTC, mushlih-almubarak commented
Oke sudah, tapi sepertinya ada [commit yang salah](https://github.com/bellshade/Javascript/pull/338/commits/2b86228534f2311a5d62f63d8c22ef4b8d1398d1) yg harusnya bukan dari saya, apa saya tutup dulu pr ini trus saya hapus branchnya, trus saya buat lagi branch baru dan saya buka lagi pr ini?

2022-09-20 17:51 UTC, reacto11mecha commented
> Oke sudah, tapi sepertinya ada [commit yang salah](https://github.com/bellshade/Javascript/pull/338/commits/2b86228534f2311a5d62f63d8c22ef4b8d1398d1) yg harusnya bukan dari saya, apa saya tutup dulu pr ini trus saya hapus branchnya, trus saya buat lagi branch baru dan saya buka lagi pr ini?

Ga usah di close, ini masalahnya tinggal benerin yang [codacy](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=10180420) kasih tau. Tinggal jalanin prettier aja sih ini.

```sh
# npm
npm run prettier

# pnpm
pnpm prettier
```

2022-09-20 18:53 UTC, mushlih-almubarak commented
Bukan itu, tapi harusnya [commit ini](https://github.com/bellshade/Javascript/commit/2b86228534f2311a5d62f63d8c22ef4b8d1398d1) (fix codeowners error) bkn dari saya, tapi saya tdk tahu knp muncul pr saya

2022-09-21 03:06 UTC, reacto11mecha commented
Hmm, ya udah di bikin pr ulang aja. Sebenernya itu dari saya tapi kayaknya efek rebase jadinya ada commit saya disitu

2022-09-21 08:54 UTC, closed without merging

2022-09-21 09:31 UTC, mushlih-almubarak commented
Ok, sudah saya buat lagi pr nya #339