feat: menambahkan fungsi untuk melarang mem-paste
bellshade/Javascript pull request #339
Opened 2022-09-21 09:29 UTC by mushlih-almubarak

Closes 

## Deskripsi (Description)
Fungsi ini berguna untuk mencegah agar user tidak bisa mempaste di inputan di form website kita.

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [x] lint testing eslint

2022-09-21 09:31 UTC, mushlih-almubarak commented
Perbaikan dari pr #338

2022-09-23 21:25 UTC, reacto11mecha requested changes
Sori baru bisa review, soalnya baru enak ngereviewnya hari ini. Buat codacy sama pesan commit dah oke, tinggal ke penulisan kodenya aja. Oiya, jangan commit suggestion nanti lupa nentuin pesan commitnya, mending di ubah di local terus di push. Kalo udah beres tinggal pencet tombol `Resolve Conversation` biar nanti di anggap beres ngubahnya.

2022-09-23 21:25 UTC, reacto11mecha commented on algorithm/WebRelated/preventPaste/prevent.js
> +// Membuat event listener jika user melakukan paste pada inputan form.
Dikasih jarak buat penulisannya

```suggestion
const input = document.querySelector("input");

// Membuat event listener jika user melakukan paste pada inputan form.
```

2022-09-23 21:25 UTC, reacto11mecha commented on algorithm/WebRelated/preventPaste/index.html
> +    input.addEventListener("paste", function (e) {
Dikasih jarak penulisannya

```suggestion
    const input = document.querySelector("input");
    
    input.addEventListener("paste", function (e) {
```

2022-09-24 07:38 UTC, mushlih-almubarak commented on algorithm/WebRelated/preventPaste/prevent.js
> +// Membuat event listener jika user melakukan paste pada inputan form.
Oke, sudah saya perbaiki

2022-09-24 07:38 UTC, mushlih-almubarak commented on algorithm/WebRelated/preventPaste/index.html
> +    input.addEventListener("paste", function (e) {
Oke, sudah saya perbaiki

2022-09-24 07:39 UTC, mushlih-almubarak commented
Oke, sudah saya perbaiki

2022-09-25 20:57 UTC, reacto11mecha approved these changes
Okey, mantap 👍

2022-09-25 23:12 UTC, KimmyKx approved these changes
LGTM

2022-09-26 06:54 UTC, merged