feat: menambahkan fungsi agar teks tidak bisa di-copy
bellshade/Javascript pull request #340
Opened 2022-10-02 14:28 UTC by mushlih-almubarak

Closes 

## Deskripsi (Description)
Fungsi ini berguna untuk mencegah agar user tidak bisa melakukan copy di tulisan yang ada di website kita.

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [x] lint testing eslint

2022-10-03 01:49 UTC, AdityaFitrianaNS commented
LGTM! 👍

2022-10-04 20:46 UTC, reacto11mecha requested changes
Makasih udah open pull request lagi, sorry baru review soalnya baru bisa review sekarang.

Untuk kode js nya kenapa ga di file terpisah aja? Soalnya biar contohnya make sense, udah ada file js terpisah yang nanti tinggal ngeselect elementnya. Coba di ubah dulu ya.

2022-10-05 02:43 UTC, mushlih-almubarak commented
Berarti buat file js baru, trus sambungin ke file HTMLnya?

2022-10-05 13:07 UTC, reacto11mecha commented
> Ooh paham, berarti kode jsnya cukup langsung ngambil dari file contoh/penjelasannya ya?
> 
> Jadi dihubungkan antara file HTML (file demonya) dengan file JS (file penjelasan dan kodenya)?

Iya kayak begitu

2022-10-05 16:12 UTC, mushlih-almubarak commented
Okey, done

2022-10-06 04:42 UTC, reacto11mecha approved these changes
Sip, LGTM :+1:

2022-10-06 10:26 UTC, mushlih-almubarak commented
Tolong tambahkan label `HACKTOBERFEST-ACCEPTED` 🙏🏻

2022-10-08 05:30 UTC, merged

2022-10-08 13:49 UTC, mushlih-almubarak commented
Btw apakah saya perlu/boleh membuat pr baru utk memperbaiki agar algoritma yg saya tambahkan [disini](https://github.com/bellshade/Javascript/pull/339) saya gabungkan/hubungkan langsung juga antara file penjelasan (file ja) dan file HTMLnya @reacto11mecha?