feat: menambahkan fungsi untuk menonaktifkan klik kanan di website kita
bellshade/Javascript pull request #342
Opened 2022-10-03 11:43 UTC by mushlih-almubarak

Closes 

## Deskripsi (Description)
Fungsi ini berguna untuk mencegah agar user tidak bisa mengklik kanan pada website kita.

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [x] lint testing eslint

2022-10-04 21:13 UTC, reacto11mecha requested changes
Makasih sekali lagi udah open pr ini lagi, tapi masalahnya masih sama kayak https://github.com/bellshade/Javascript/pull/340#pullrequestreview-1130592358.

Kode js nya satu aja, html khusus buat element html nya aja, ada file js terpisah yang udah ada penjelasannya, nah html nya nanti manggil si jsnya.

2022-10-05 15:57 UTC, mushlih-almubarak commented
Done

2022-10-06 04:44 UTC, reacto11mecha approved these changes

2022-10-06 10:26 UTC, mushlih-almubarak commented
Tolong tambahkan label `HACKTOBERFEST-ACCEPTED` 🙏🏻

2022-11-25 18:26 UTC, closed without merging

2022-11-25 18:32 UTC, mushlih-almubarak commented
Oke, sudah saya close yang ini dan buat baru: #361