docs: menghapus "Navbar" dari contoh penggunaan JavaScript
bellshade/Javascript pull request #343
Opened 2022-10-03 12:10 UTC by mushlih-almubarak

Closes 

## Deskripsi (Description)
Contoh navbar yang ada pada link tersebut tidak ada hubungannya sama sekali dengan JavaScript, itu hanya navbar biasa menggunakan HTML dan CSS, tidak ada JavaScriptnya sama sekali.

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [x] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [x] lint testing eslint

2022-10-04 04:49 UTC, dhafitf approved these changes

2022-10-04 20:35 UTC, reacto11mecha commented
Terimakasih sudah berkontribusi ke bellshade repo javascript.

Sebelumnya mau tanya, apa alasannya contoh navbar mesti dihapus ya?

2022-10-05 02:40 UTC, mushlih-almubarak commented
Terimakasih atas jawabannya, kan alasannya sudah saya tulis di deskripsi pr dari awal, yaitu karna navbarnya gk pakai JavaScript sama sekali

2022-10-05 13:11 UTC, reacto11mecha requested changes
Ada kok, penulisan urlnya ada yang salah makanya js nya ga muncul

2022-10-05 13:11 UTC, reacto11mecha commented on README.md
> +4. [Game Sederhana](https://codepen.io/msval/pen/qKhcD)
```suggestion
4. [Navbar](https://codepen.io/abdosteif/pen/bRoyMb)
5. [Game Sederhana](https://codepen.io/msval/pen/qKhcD)
```

2022-10-05 14:37 UTC, mushlih-almubarak commented on README.md
> +4. [Game Sederhana](https://codepen.io/msval/pen/qKhcD)
Ooh iya ternyata memang ada, cmn gk keliatan karna URLnya saya. Okey, sekarang sudah diperbaiki

2022-10-05 14:38 UTC, mushlih-almubarak commented
Ooh iya ternyata memang ada, cmn gk keliatan karna URLnya salah. Okey, sekarang sudah diperbaiki

2022-10-06 05:13 UTC, merged

2022-10-06 10:25 UTC, mushlih-almubarak commented
Tolong tambahkan label `HACKTOBERFEST-ACCEPTED` 🙏🏻