feat : pohon faktor/factor tree on algorithm/math
bellshade/Javascript pull request #345
Opened 2022-10-04 02:48 UTC by MoonLGH

## Deskripsi (Description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux` (algorithm di tes di gitpod dengan linux)

## Testing

- [x] doctesting js
- [x] lint testing eslint

2022-10-04 20:59 UTC, reacto11mecha requested changes
Terimakasih sudah berkontribusi ke bellshade repositori javascript, makasih juga udah jalanin prettiernya.

Untuk penulisan kodenya tolong dikasih jarak ya biar si kode nya ada "nafas" nya, kalo dempet banget ga enak nanti dibacanya, juga kalo tipe variabelnya pake `let` atau `const`. Tapi ini kan variabelnya di re assign, jadinya pake let aja. Tolong di ubah ya di local.

2022-10-04 20:59 UTC, reacto11mecha commented on algorithm/math/factorTree.js
> +  while (number > 1 && number % 2 === 0) {
```suggestion
  let array = [];
  let s = 6;
  
  while (number > 1 && number % 2 === 0) {
```

2022-10-04 20:59 UTC, reacto11mecha commented on algorithm/math/factorTree.js
> +  while (number > 2 && number % 3 === 0) {
```suggestion
  }
  
  while (number > 2 && number % 3 === 0) {
```

2022-10-04 20:59 UTC, reacto11mecha commented on algorithm/math/factorTree.js
> +    while (number > 4 && number % p === 0) {
```suggestion
  }
  
  while (number > 4) {
    let p = s - 1;
    let q = s + 1;
    
    while (number > 4 && number % p === 0) {
```

2022-10-04 20:59 UTC, reacto11mecha commented on algorithm/math/factorTree.js
> +    while (number > 4 && number % q === 0) {
```suggestion
    }
    
    while (number > 4 && number % q === 0) {
```

2022-10-04 20:59 UTC, reacto11mecha commented on algorithm/math/factorTree.js
> +    s += 6;
```suggestion
    }
    
    s += 6;
```

2022-10-04 20:59 UTC, reacto11mecha commented on algorithm/math/factorTree.js
> +  return array;
```suggestion
  }
  
  return array;
```

2022-10-04 21:09 UTC, reacto11mecha commented
Oiya, pesan commit ada yang [salah](https://www.commitcheck.com/status/bellshade/Javascript/025f8dc1-ec89-4e34-b97f-71f0f0d9555c), nah itu perlu dibenerin dulu. Coba benerin dulu apa udah dijelaskan sebelumnya, baru benerin commit messagenya.

Caranya direbase dulu ke commit [`7f3a4ad`](https://github.com/bellshade/Javascript/pull/345/commits/7f3a4ad9667be091db7c2ddbf487b4bdc2bcf6b2), caranya
```sh
git rebase --interactive '7f3a4ad^'
```

Nanti akan kebuka editor default gitnya, terus edit baris yang ada `7f3a4ad` yang awalnya `pick` jadi `edit`.

Kalo udah di save baru di ubah pesan commitnya.
```sh
git commit --all --amend --no-edit -m "feat: pohon faktor/factor tree on algorithm/math"
```

Setelahnya di rebase continue biar balik ke commit yang paling baru
```sh
git rebase --continue
```

Nah setelahnya baru di push, tapi mesti di `force`.
```sh
git push --force
```

2022-10-04 23:24 UTC, MoonLGH commented
oops, aku reflek pake var karena matematika ingetnya ke variable, maaf maaf, nanti ku benerin di lab sekolah

2022-10-04 23:58 UTC, reacto11mecha commented
> oops, aku reflek pake var karena matematika ingetnya ke variable, maaf maaf, nanti ku benerin di lab sekolah

Gapapa, benerin aja dulu

2022-10-05 13:29 UTC, reacto11mecha commented
Punten, ada masalah ngebenerin pesan commit?

2022-10-05 13:35 UTC, MoonLGH commented
nyata, benar sekali

2022-10-05 13:43 UTC, MoonLGH commented
tadi aku a commit changes dari website githubnya, jadi manual 1 1, dan commit nya manual gitu

2022-10-05 13:45 UTC, MoonLGH commented
tapi overall udah bener semua

2022-10-06 04:56 UTC, reacto11mecha commented
Atau ga gini aja deh, close pull requestnya, di fork ulang soalnya kalo diliat kamu ga bikin branch baru.

Nah file yang algoritma kamu disalin ke tempat lain, nanti di salin lagi ke branch yang baru itu, commit, push, open pr lagi

2022-10-06 05:12 UTC, MoonLGH commented
baiklah, aku clone dari pr aja apa ya ?

2022-10-06 05:12 UTC, MoonLGH commented
closing

2022-10-06 05:12 UTC, closed without merging

2022-10-06 05:17 UTC, reacto11mecha commented
> baiklah, aku clone dari pr aja apa ya ?

Salin aja apa yang ada di lokal