add: array manipulation - findIndex
bellshade/Javascript pull request #351
Opened 2022-10-11 07:17 UTC by rickyjulpiter

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `macOS`

## Testing

- [x] doctesting js
- [x] lint testing eslint

2022-10-11 22:50 UTC, reacto11mecha requested changes
Sebelumnya terimakasih sudah berkontribusi ke bellshade repositori javascript.

Untuk pull requestnya tolong di tambahin penjelasan di [README.md](https://github.com/bellshade/Javascript/blob/main/learn/Basic/010_array_manipulation/README.md) yang ada di setiap materi foldernya.

Dan pull request #352 itu dijadiin satu aja, sama-sama butuh penjelasan dan pasti conflict kalo tetep ke pisah.

2022-10-12 03:41 UTC, rickyjulpiter commented
Hi @reacto11mecha . Untuk penjelasan di README.md sudah ditambahkan. Dan untuk kemungkinan issue conflict antara 2 PR #351 dan #352, saya sudah melakukan sync antara kedua branch, jadi seharusnya tidak ada kemungkinan conflict. 

Thank you.

2022-10-13 11:58 UTC, reacto11mecha commented
Sori baru jawab, baru ada waktunya hari ini soalnya sibuk sama urusan lain.

Punten, ini di sync tapi ya validnya cuman 1 pull request, soalnya kan #352 penjelasannya itu ada di pull request ini, gimana kalo yang itu di close aja tapi lanjut yang ini aja.

2022-10-17 15:44 UTC, dhafitf approved these changes
Dokumentasi sudah oke

2022-10-18 01:54 UTC, reacto11mecha approved these changes
Sip kodenya udah oke, LGTM 👍

2022-10-18 01:55 UTC, merged