docs: menambahkan materi set operators
bellshade/Javascript pull request #355
Opened 2022-10-19 16:51 UTC by fhasnur

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

2022-10-19 20:12 UTC, reacto11mecha requested changes
Terimakasih sudah berkontribusi ke bellshade repositori JS.

Kalau dilihat dari materi penjelasan sudah cukup menerangkan kegunaan `Set`, tinggal beberapa code style yang perlu di benerin. Tinggal jalanin prettiernya aja terus ubah `let` jadi `const` soalnya valuenya ga akan berubah.

Terus buat masalah comment, dikasih space dari si `//`, biar ada "nafas" nya. Semisal `//Irisan` harusnya `// Irisan`, berlaku juga buat yang tertulis di readme.

2022-10-20 12:30 UTC, fhasnur commented
> Terimakasih sudah berkontribusi ke bellshade repositori JS.
> 
> Kalau dilihat dari materi penjelasan sudah cukup menerangkan kegunaan `Set`, tinggal beberapa code style yang perlu di benerin. Tinggal jalanin prettiernya aja terus ubah `let` jadi `const` soalnya valuenya ga akan berubah.
> 
> Terus buat masalah comment, dikasih space dari si `//`, biar ada "nafas" nya. Semisal `//Irisan` harusnya `// Irisan`, berlaku juga buat yang tertulis di readme.

Segera saya perbaiki

2022-10-22 00:23 UTC, reacto11mecha commented
Commit nya belum dikasih prefix makanya ga lolos, coba di benerin dulu, jangan lupa jalanin prettiernya....

2022-10-25 09:54 UTC, reacto11mecha commented
Punten @fhasnur, masih bermasalah kah sama commitnya?

2022-11-01 13:22 UTC, fhasnur commented
> Punten @fhasnur, masih bermasalah kah sama commitnya?

Iya :v

2022-11-01 13:34 UTC, fhasnur commented
Masih belum paham fixing nya wkwk

2022-11-13 10:58 UTC, reacto11mecha requested changes
Aduh sori mas baru jawab, telat banget soalnya ada tugas yang lain :pray: 

Ini errornya ada dua, ada masalah di pesan commit sama di codacy.

Kalo di codacy itu jalanin aja prettier bawaan repo ini, kalo di liat-liat formatter code editor punya mas itu settingannya beda, makanya yang awalnya bener malah error lagi. Buat jalanin prettier tinggal execute `npm run prettier`.

Kalo buat pesan commit agak tricky mas, perlu di rebase segala macem. Saran saya sih ulangin lagi prosesnya, hapus branch, terus buat branch ulang lagi, nah abis tu di push, open pr nya lagi.

2022-11-25 16:28 UTC, fhasnur commented
oke siap mas hehe, saya juga baru lihat lagi ini PR, lama banget gak saya solve wkwk

2022-12-18 12:58 UTC, LintangDev commented
ini pr belum ada update 3 minggu ini apakah ada konfirmasi? jika tidak ada komfirmasi dalam 3 hari saya close ya prnya mas

2022-12-21 10:54 UTC, LintangDev commented
Baik karena tidak ada konfirmasi dalam 3 hari untuk pr ini saya close ya.

2022-12-21 10:54 UTC, closed without merging