Keyword this
bellshade/Javascript pull request #364
Opened 2023-01-01 18:00 UTC by azhardanii

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya menambah dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [ ] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

2023-01-02 10:05 UTC, reacto11mecha requested changes
Sebelumnya makasih udah coba kontribusi ke bellshade repo javascript walaupun agak try hard ya kalo diliat liat :sweat_smile:, tapi gakpapa namanya juga belajar.

Mungkin yang perlu di kasih tau pertama, prefix commit messagenya di liat lagi, kalo `docs` itu spesifik ke file markdown, kalo `fix` itu ke file js. Diperhatikan yah abis ini kalo mau commit sesuatu.

Yang kedua, template yang dikasih di awal-awal open pull request jangan di ubah-ubah, itu tinggal di centang aja, tinggal kasih `x` didalemnya.

Ketiga, dari code style, entah itu readme atau file js biasa. Tolong dikasih "nafas" tiap sintaks kode yang emang dirasa perlu dikasih. Kalo buat yang file markdown, semisal ada code block, itu dikasih jarak antara teks biasa sama code blocknya. Kayak di `learn/Functional/007_Keyword_This/README.md` itu juga masih dempet banget.

Oiya, yang dibawah itu jangan commit langsung, nanti nyepam mendingan di ubah di lokal aja. Kalo udah di benerin, jangan lupa pencet `Resolve Conversation`.

2023-01-03 07:31 UTC, reacto11mecha requested changes
Nganu mas, ada yang perlu di ubah lagi. Di readmenya ga usah dikasih garis (`---`), soalnya readme yang lain gak pake garis, nanti tampilannya ga konsisten.

2023-01-03 09:04 UTC, KimmyKx requested changes
Terima kasih kak udah bersedia kontribusi emang mantap bener effortnya, tapi banyak juga ya commitnya 😅 jadi menurut aku gini, buat request yang baru aja kak dan yang ini ditutup dulu, trus cukup masukin/commit materi yang mau ditambahkan saja kayak Keyword This udah bagus banget dan syntax fixnya di file lain ga usah terlalu banyak kak, gimana?

2023-01-05 17:53 UTC, reacto11mecha commented
Gimana mas @azhardanii? enaknya di close dulu pr yang ini. Sori ya kalo open close terus dari kemarin :pray:

2023-01-05 18:10 UTC, azhardanii commented
> 

ooo iya siap kak, maaf maaf slowres, barun keluar dari pedalaman,, :v

2023-01-05 18:46 UTC, closed without merging