docs: Menambahkan Dokumentasi Function Scope dan Keyword This
bellshade/Javascript pull request #366
Opened 2023-01-05 19:50 UTC by azhardanii

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

2023-01-08 04:02 UTC, reacto11mecha requested changes
Sori ya baru cek, baru ngeh pas ngecek notif github. Selagi nunggu maintainer yang lain, mungkin benerin ini dulu aja

2023-01-08 08:44 UTC, azhardanii commented on learn/Basic/008_function/functionScope.js
> +// eslint-disable-next-line no-undef
ooo okay kak, otewee,, 🚀

2023-02-04 12:19 UTC, slowy07 approved these changes
LGTM

2023-02-04 12:19 UTC, merged

2023-02-04 16:55 UTC, azhardanii commented
tinkyuu kak,, ✨