add: menambahkan basic operator perbandingan (belum selesai sepenuhnya)
bellshade/Javascript pull request #37
Opened 2021-09-22 21:04 UTC by reacto11mecha

Closes #27

## Deskripsi (Description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya memperbaiki dokumentasi
- [x] saya menambah dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux`

## Testing

- [x] doctesting js
- [x] lint testing eslint

## Maintainer
@bellshade/javascript-team
@bellshade/docs-team

2021-09-23 05:48 UTC, nomadkode approved these changes
secara dokumentasi ga ada masalah

2021-09-23 09:35 UTC, slowy07 requested changes
coba cek di check pull [37](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=8127493), klo mmng faktor disengaja, request @bellshade/javascript-team

2021-09-23 11:52 UTC, reacto11mecha commented
Hmm, akhirnya fix juga. Kalo settingan es lint nya ga diubah bakalan lebih banyak kode yang dikorbanin. Sekarang cuma 4 baris di comment.

2021-09-23 11:58 UTC, hendraaagil commented
kalau masih pengen dilanjutin, bisa convert to draft dulu
kalau sudah siap review bisa open PR nya lagi @reacto11mecha 
![image](https://user-images.githubusercontent.com/54741166/134502780-62ea86bf-c9b5-42ad-a9df-d65c611bb6a3.png)

2021-09-23 11:59 UTC, reacto11mecha commented
> kalau masih pengen dilanjutin, bisa convert to draft dulu
> kalau sudah siap review bisa open PR nya lagi @reacto11mecha
> ![image](https://user-images.githubusercontent.com/54741166/134502780-62ea86bf-c9b5-42ad-a9df-d65c611bb6a3.png)

Hmmm, oke deh jadiin draft dulu

2021-09-23 14:35 UTC, hendraaagil requested changes

2021-09-23 14:35 UTC, hendraaagil commented on basic/README.md
> +- [Hello world](https://github.com/bellshade/Javascript/blob/main/basic/helloWorld.js)
karena ini README di folder basic, jadi untuk ngarahin ke file helloWorld.js bisa pakai url `helloWorld.js` aja
kalau di folder seperti yang bawahnya ini pakai url `variable_datatype/variableAndDataTypes1.js`
siapa tau nanti bakal ganti nama repositori, jadi refactor banyak url nanti 😂

2021-09-24 00:12 UTC, reacto11mecha commented on basic/README.md
> +- [Hello world](https://github.com/bellshade/Javascript/blob/main/basic/helloWorld.js)
Hmm, oke ku ganti dulu

2021-09-24 00:27 UTC, reacto11mecha commented
Apa perlu ngubah settingan prettier ? Dari kemaren gini terus, masalah di markdownnya.

2021-09-24 02:26 UTC, hendraaagil commented
masalah apa tuh? @reacto11mecha

2021-09-24 02:29 UTC, reacto11mecha commented
> masalah apa tuh? @reacto11mecha

Cek codacy https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=8127493

2021-09-24 07:43 UTC, hendraaagil commented
oalah, itu butuh line baru @reacto11mecha 
jadi gini markdown listnya:
```
- list 1

- list 2

- list 3
```

2021-09-24 07:50 UTC, hendraaagil approved these changes

2021-09-25 11:00 UTC, AlfatArdiansa approved these changes
LGTM 👏

2021-09-25 11:01 UTC, AlfatArdiansa commented
![gambar](https://user-images.githubusercontent.com/53366314/134769109-ebf02b23-7525-4f90-bbdc-c6bf7648f044.png)
Wait a minute

2021-09-25 11:15 UTC, reacto11mecha commented
> ![gambar](https://user-images.githubusercontent.com/53366314/134769109-ebf02b23-7525-4f90-bbdc-c6bf7648f044.png)
> Wait a minute

File `BASIC.md` di root nya di ubah, jadi kena conflict. Cek https://github.com/bellshade/Javascript/commit/5090ee8712251ee554d16822a586508b7ae88cd1

2021-09-25 12:11 UTC, merged