feat: algoritma perkalian matrix
bellshade/Javascript pull request #375
Opened 2023-04-02 02:13 UTC by fauzan-radji

Closes 

## Deskripsi (Description)

Algoritma ini digunakan untuk melakukan perkalian antara dua matrix. Sebuah matrix direpresentasikan dengan array dua dimensi berisi number.

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [x] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux`

## Testing

- [x] doctesting js
- [ ] lint testing eslint

2023-04-02 04:07 UTC, reacto11mecha requested changes
Makasih udah open pr, tapi ada yang perlu di ubah lagi biar ga kena error codacy

2023-04-02 04:07 UTC, reacto11mecha commented on algorithm/math/matrix.js
> +  for (let i = 0; i < dimensi1.rows; i++) matrixHasil[i] = [];
```suggestion
  for (let i = 0; i < dimensi1.rows; i++) {
    matrixHasil[i] = [];
  }
```

2023-04-02 04:07 UTC, reacto11mecha commented on algorithm/math/matrix.js
> +        matrixHasil[i][j] += matrix1[i][x] * matrix2[x][j];
```suggestion

      for (let x = 0; x < dimensi1.cols; x++) {
        matrixHasil[i][j] += matrix1[i][x] * matrix2[x][j];
      }
```

2023-04-02 09:50 UTC, fauzan-radji commented
> Makasih udah open pr, tapi ada yang perlu di ubah lagi biar ga kena error codacy

Sudah saya perbaiki untuk kurawalnya

2023-04-09 04:17 UTC, slowy07 requested changes
ubah dari nama filenya ``matrix.js`` ke ``perkalianMatrix.js`` atau ``matrixMultiplication.js``

2023-04-09 20:24 UTC, fauzan-radji commented
> ubah dari nama filenya ``matrix.js`` ke ``perkalianMatrix.js`` atau ``matrixMultiplication.js``

Rencananya kedepannya file ``matrix.js`` ini akan saya isi dengan operasi-operasi matrix lainnya. Oleh karena itu saya menggunakan nama yang lebih umum. Apakah masih perlu diganti?

2023-04-09 22:52 UTC, slowy07 commented
kalo seperti itu boleh, maka ubah aja dulu sementara pull requestnya ke draft untuk menambahkan operasi-operasi atau tambahan-tambahan lainnya

2023-04-26 05:17 UTC, reacto11mecha commented
Gimana @fauzan-radji? Ada update?

2023-06-30 20:46 UTC, slowy07 commented
pull request closed, stale

2023-06-30 20:46 UTC, closed without merging