add: menambah artikel tentang Intl
bellshade/Javascript pull request #376
Opened 2023-04-02 07:07 UTC by Tio-pratomo

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [x] doctesting js
- [x] lint testing eslint

2023-04-02 13:21 UTC, Tio-pratomo commented
saya bingung semua kode yang dicoba selalu "The numeric literal will have at different value at runtime." padahal sudah diganti-ganti dengan supaya sesuai tetapi selalu gagal di codacy

2023-04-03 14:13 UTC, reacto11mecha commented
Sebentar, ini mau nambahin materi tentang Intl doang atau mau sekalian sama nullish coaslescing?

2023-04-03 15:00 UTC, Tio-pratomo commented
> Sebentar, ini mau nambahin materi tentang Intl doang atau mau sekalian sama nullish coaslescing?
Iya mas sekalian aja.

2023-04-03 15:01 UTC, Tio-pratomo commented
> Coba di fix lagi, balikin ke `86_400_000` si millisecondnya

waduh, tadi awalnya juga begitu, tapi gagal. Agak bingung juga soalnya itu udah bilangan valid bahkan belum nyentuh type bigInt.

2023-04-04 08:30 UTC, reacto11mecha commented
> > Coba di fix lagi, balikin ke `86_400_000` si millisecondnya
> 
> waduh, tadi awalnya juga begitu, tapi gagal. Agak bingung juga soalnya itu udah bilangan valid bahkan belum nyentuh type bigInt.

Sebelumnya udah ngeh kalo workflownya udah di approve?

2023-04-04 13:11 UTC, reacto11mecha commented
> > Sebelumnya udah ngeh kalo workflownya udah di approve?
> 
> ga tau mas, gagalnya ya di codacy aja. Apa ga perlu pakai sample kode aja ya biar jalan?. Apakah repo ini jika yang pull request, testnya oke, langsung merge otomatis?

Nggak, gak di merge otomatis. Kalo emang nemuin masalah yang sama ya artinya jangan kasih contoh angka yang gede banget

2023-04-08 14:09 UTC, reacto11mecha requested changes
Mungkin ini revisi yang perlu di ubah, inget juga kalo commit file js yang sifatnya ngubah kode prefixnya "fix",  kalo file js sama md yang sifatnya penjelasan prefixnya "docs"

Oiya, nama foldernya jangan `JavascriptStandardLibrary`, `StandardLibrary` aja. Terus setiap file js nya di kasih penjelasan, kode yang dijalankan bakalan ngapain.

2023-04-08 14:09 UTC, reacto11mecha commented on learn/Basic/015_nullish_coalescing_operator/README.md
> +const valD = nullValue ?? undefined;
Hapus aja, gak kepake juga kan valuenya

2023-04-09 00:37 UTC, closed without merging