add: materi WebApi Fetch
bellshade/Javascript pull request #393
Opened 2023-10-06 08:18 UTC by adikurniawanid

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [X] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [X] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [X] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [X] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux / windows`

## Testing

- [X] doctesting js
- [X] lint testing eslint

2023-10-06 12:20 UTC, reacto11mecha requested changes
Terimakasih sudah mau berkontribusi ke repositori javascript, mungkin ada beberapa hal yang harus di ubah sebelum PR ini di merge.

Sebelumnya commit pertama itu prefixnya `add` yang seharusnya `feat`. Di toleransi, tapi PR selanjutnya di usahakan pake `feat`.

Kemudian dokumentasi ada beberapa saran yang ditambahkan, tetapi kalau bisa penjelasannya dikembangkan lagi, supaya orang yang baru belajar lebih paham akan penggunaan fetch ini.

> Jangan lupa, kalo markdown pake `docs: ` prefixnya.

Terimakasih!

2023-10-06 12:20 UTC, reacto11mecha commented on learn/WebApi/fetch/README.md
> +Fetch API adalah antarmuka JavaScript yang memungkinkan untuk mengirim dan menerima permintaan HTTP secara asinkron. Fetch API memungkinkan untuk berkomunikasi dengan server dalam mengambil, mengirim
```suggestion
Fetch API adalah antarmuka JavaScript yang memungkinkan web klien untuk mengirim dan menerima permintaan HTTP secara asinkron. Fetch API memungkinkan untuk berkomunikasi dengan server dalam mengambil, mengirim, dan memproses data pada aplikasi web dengan metode HTTP seperti GET, POST, PUT, dan DELETE serta menangani kesalahan dengan baik.
```

2023-10-06 13:55 UTC, reacto11mecha commented
Help bang @slowy07, codacy in progress terus badgenya

2023-10-11 11:23 UTC, slowy07 commented
passed no issue @reacto11mecha on ``codacy``

2023-10-14 03:33 UTC, reacto11mecha commented
Punten @adikurniawanid, gimana statusnya? Kalo belum ada update 2 hari lagi, PR ini bakalan di tutup

2023-10-14 11:12 UTC, slowy07 commented
codacy check success [#393](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=12774478), @reacto11mecha

2023-10-14 15:46 UTC, reacto11mecha approved these changes
LGTM!

2023-10-16 15:56 UTC, slowy07 approved these changes
LGTM, terima kasih atas kontribusinya @adikurniawanid

2023-10-16 15:57 UTC, merged