add: menambahkan algoritma baru
bellshade/Javascript pull request #396
Opened 2023-10-17 19:30 UTC by rikarani

Closes 

## Deskripsi (Description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya menambahkan materi/sub materi belajar
- [ ] saya memperbaiki materi/sub materi belajar
- [ ] saya menambah dokumentasi
- [ ] saya memperbaiki dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [x] lint testing eslint

2023-10-18 17:07 UTC, rikarani commented
bang ini analysis dari codacy harus pass kah?

2023-10-20 14:39 UTC, slowy07 requested changes
terima kasih atas kontribusinya @rikarani ,untuk passing dari precision number literal, mungkin kamu bisa mencoba dengan menggunakan notasi scientific untuk angka

2023-10-21 01:42 UTC, rikarani commented
makasih sarannya bang @slowy07, ntar saya coba terapin

2023-10-21 18:20 UTC, rikarani commented
waduh, ini codacy 😭 😭 udah diubah pdhl

2023-10-26 02:07 UTC, slowy07 approved these changes
LGTM, terima kasih atas kontribusinya @rikarani

2023-10-26 02:08 UTC, merged