fix: add switch case
bellshade/Javascript pull request #62
Opened 2021-10-03 15:12 UTC by hendraaagil

Closes 

## Deskripsi (Description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya memperbaiki dokumentasi
- [x] saya menambah dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [x] doctesting js
- [x] lint testing eslint

## Maintainer
**maintainer javascript**
@bellshade/javascript-team

**maintainer dokumentasi**
@bellshade/docs-team

2021-10-03 22:16 UTC, wanrabbae approved these changes

2021-10-03 22:41 UTC, reacto11mecha requested changes

2021-10-03 22:41 UTC, reacto11mecha commented on basic/005_conditioning/README.md
>  Lihat kode lengkapnya [disini](conditionalStatements.js).
Update juga dokumentasinya biar ngarahin ke filenya langsung

2021-10-04 01:36 UTC, hendraaagil commented on basic/005_conditioning/README.md
>  Lihat kode lengkapnya [disini](conditionalStatements.js).
kan filenya sama wkwk

2021-10-04 04:47 UTC, reacto11mecha approved these changes

2021-10-04 05:19 UTC, merged