add: menambahkan algoritma rot13 pada folder chiper
bellshade/Javascript pull request #63
Opened 2021-10-03 16:17 UTC by ezza022

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan algoritma terbaru

## Contributor Requirements (Syarat Kontributor)

- [ ] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

## Maintainer

2021-10-03 19:07 UTC, slowy07 requested changes
terima kasih atas kontribusinya @ezza022 , kami menyarankan untuk menambah kembali sedikit penjelasan dan mengurangi penggunaan kode yang bersifat satu line agar yang lainnya bisa mengerti pada kode tersebut, terima kasih!

2021-10-03 19:07 UTC, slowy07 commented on cipher/rot13.js
> +      var start = chr <= 'Z' ? 65 : 97;
```suggestion
      var start = chr <= "Z" ? 65 : 97;
```
menggunakan tanda petik dua

2021-10-03 19:07 UTC, slowy07 commented on cipher/rot13.js
> +const rot13onliner = str => str.replace(/[a-zA-Z]/g,chr=>String.fromCharCode((chr <= 'Z' ? 65 : 97)+(chr.charCodeAt(0)-(chr <= 'Z' ? 65 : 97)+13)%26))
menggunakan tanda petik 2 dan disarankan tidak menggunakan sistem satu line coding yang begitu kompleks agar yang lainnya pada paham pada kodingannya

2021-10-03 19:10 UTC, ezza022 commented on cipher/rot13.js
> +const rot13onliner = str => str.replace(/[a-zA-Z]/g,chr=>String.fromCharCode((chr <= 'Z' ? 65 : 97)+(chr.charCodeAt(0)-(chr <= 'Z' ? 65 : 97)+13)%26))
baik akan saya perbaiki

2021-10-03 21:03 UTC, reacto11mecha requested changes
Easy fix tinggal jalanin prettiernya aja, abis itu commit

```bash
npm run prettier
```

2021-10-04 06:55 UTC, reacto11mecha requested changes

2021-10-04 06:55 UTC, reacto11mecha commented on cipher/rot13.js
> +console.log(rot13("uryyb jbeyq")) //hello world
Tinggal ditambahin aja `;` buat ngefix codacy nya

```suggestion
console.log(rot13("hello world")); //uryyb jbeyq
console.log(rot13("uryyb jbeyq")); //hello world
```

2021-10-04 06:55 UTC, hendraaagil requested changes

2021-10-04 06:55 UTC, hendraaagil commented on cipher/rot13.js
> +console.log(rot13("hello world")) //uryyb jbeyq
```suggestion
console.log(rot13("hello world")); //uryyb jbeyq
```
kurang ;

2021-10-04 06:55 UTC, hendraaagil commented on cipher/rot13.js
> +console.log(rot13("uryyb jbeyq")) //hello world
```suggestion
console.log(rot13("uryyb jbeyq")); //hello world
```
ini juga

2021-10-04 07:28 UTC, ezza022 commented on cipher/rot13.js
> +console.log(rot13("hello world")) //uryyb jbeyq
ohiya lupa

2021-10-04 07:37 UTC, hendraaagil approved these changes

2021-10-04 07:39 UTC, reacto11mecha approved these changes

2021-10-04 07:43 UTC, merged

2021-10-05 05:45 UTC, nomadkode reviewed
terima kasih @ezza022 sudah berkontribusi di bellshade. 😄