menambahkan type of
bellshade/Javascript pull request #67
Opened 2021-10-04 02:33 UTC by MaxdhaMax

## Deskripsi (Description)

- [ ] saya menambahkan type off untuk mengecek tipe data dari sebuah variabel

## Contributor Requirements (Syarat Kontributor)

- [ ] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = ` windows`

## Testing

- [ ] doctesting js
- [ ] lint testing eslint

## Maintainer

2021-10-04 05:17 UTC, reacto11mecha commented
Deskripsi yang udah ada jangan diubah ya, maintainer juga di tag sesuai sama yang udah diubah. Udah baca belum file panduan kontribusinya, pesan commitnya juga ada yang salah. Silahkan baca terus dibenerin dulu, amend commit nya terus push force.

Terima Kasih

2021-10-04 06:04 UTC, MaxdhaMax commented
sudah saya betulkan yaa kak, mohon untuk dicek lagi

2021-10-04 06:56 UTC, wanrabbae commented
Diliat dari [sini](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=8183954) itu masalah penulisan sintaks.
jalanin prettiernya aja trs commit lalu pr. agar lulus check

```bash
npm run prettier
```

2021-10-04 07:18 UTC, wahyall approved these changes

2021-10-04 07:35 UTC, reacto11mecha requested changes

2021-10-04 07:35 UTC, reacto11mecha commented on basic/002_variable_datatype/README.md
> +
Kalo diliat [disini](https://app.codacy.com/gh/bellshade/Javascript/pullRequest?prid=8183954), ada yang kelebihan baris. Mesti dihapus.

```suggestion
```

2021-10-04 07:47 UTC, MaxdhaMax commented
oke sudah saya betulkan kak

2021-10-04 07:53 UTC, reacto11mecha requested changes
Hmm, di readmenya tambahin section penjelasannya soal dong tentang `typeof`

2021-10-04 07:55 UTC, dydrmr5 approved these changes

2021-10-04 08:27 UTC, MaxdhaMax commented
baik sudah kak

2021-10-04 08:34 UTC, reacto11mecha approved these changes
Hmm, masi ada yang salah sih, tapi nanti team dokumentasi bakalan benerin dokumentasinya. Terima kasih atas kontribusinya :+1:

2021-10-04 08:35 UTC, merged

2021-10-05 05:54 UTC, nomadkode reviewed
terima kasih @MaxdhaMax sudah berkontribusi di bellshade. 😄