add: es6 dan isi foldernya
bellshade/Javascript pull request #79
Opened 2021-10-04 14:38 UTC by fhasnur

Closes 

## Deskripsi (Description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya memperbaiki dokumentasi
- [x] saya menambah dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [x] doctesting js
- [x] lint testing eslint

## Maintainer

2021-10-04 23:49 UTC, reacto11mecha requested changes
Tolong ditambahin contoh filenya juga di setiap materinya

2021-10-04 23:49 UTC, reacto11mecha commented on es6/002_variable/README.md
> +
```suggestion
```

Tolong dihapus baris yang kelebihan

2021-10-05 00:13 UTC, dydrmr5 reviewed
Bahasa penjelasannya sudah baik. Tinggal lakukan beberapa perbaikan sesuai dengan arahan om @reacto11mecha ya.
Setelah semuanya pas, pasti akan kita merge.
Terima kasih atas kontribusinya 👍🏼

2021-10-05 07:47 UTC, fhasnur commented on es6/002_variable/README.md
> +
Siap om

2021-10-05 07:48 UTC, fhasnur commented on es6/002_variable/README.md
> +
Gass

2021-10-05 08:49 UTC, reacto11mecha commented
Btw pesan commit di repo ini ada update, commit saat ini biarin aja dulu. Kalo ada error lagi mau ngefix pesan commitnya harus berubah

https://github.com/bellshade/Javascript/blob/main/CONTRIBUTING.md#pesan-commit

2021-10-05 09:29 UTC, reacto11mecha requested changes

2021-10-05 09:29 UTC, reacto11mecha commented on es6/002_variable/variable.js
> +minuman = "susu";
Yang ini nimbulin error di codacy sama codefactor, di comment aja

```suggestion
// minuman = "susu";
```

2021-10-05 09:29 UTC, reacto11mecha commented on es6/003_arrow_function/arrowFunction.js
> +    'Papua'
Mesti make doublequute, jangan single quute. Easy fix jalanin prettiernya

```bash
npm run prettier
```

```suggestion
    "Sumatera",
    "Jawa",
    "Kalimantan",
    "Sulawesi",
    "Papua"
```

2021-10-05 09:29 UTC, reacto11mecha commented on es6/003_arrow_function/arrowFunction.js
> +console.log((islands.map(island => island.length))); // [8, 4, 10, 8 , 5]
Ada kelebihan tanda kurung sama ada yang kurang

```suggestion
console.log(islands.map((island) => island.length)); // [8, 4, 10, 8 , 5]
```

2021-10-05 09:37 UTC, fhasnur commented on es6/002_variable/variable.js
> +minuman = "susu";
siap

2021-10-05 09:37 UTC, fhasnur commented on es6/003_arrow_function/arrowFunction.js
> +    'Papua'
siap gass

2021-10-05 09:38 UTC, fhasnur commented on es6/003_arrow_function/arrowFunction.js
> +console.log((islands.map(island => island.length))); // [8, 4, 10, 8 , 5]
siap ane fix kan dlu

2021-10-05 09:41 UTC, reacto11mecha commented on es6/003_arrow_function/arrowFunction.js
> +console.log((islands.map(island => island.length))); // [8, 4, 10, 8 , 5]
sip :+1:

2021-10-05 09:41 UTC, reacto11mecha commented on es6/003_arrow_function/arrowFunction.js
> +console.log((islands.map(island => island.length))); // [8, 4, 10, 8 , 5]
Kalo udah `Resolve conservation` nya ya

2021-10-05 10:15 UTC, reacto11mecha approved these changes

2021-10-05 10:31 UTC, nomadkode approved these changes
docs LGTM 👍🏼

2021-10-05 11:02 UTC, hendraaagil approved these changes

2021-10-05 11:03 UTC, merged

2021-10-05 11:03 UTC, hendraaagil commented
🚀