add : Menambahkan kondisi operator Ternary
bellshade/Javascript pull request #81
Opened 2021-10-04 16:17 UTC by AndriP8

Closes 

## Deskripsi (Description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [ ] saya memperbaiki dokumentasi
- [x] saya menambah dokumentasi

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `windows`

## Testing

- [x] doctesting js
- [x] lint testing eslint

## Maintainer

2021-10-04 23:17 UTC, reacto11mecha requested changes

2021-10-04 23:17 UTC, reacto11mecha commented on basic/005_conditioning/conditionalStatements.js
> +console.log("Hasil Operator Ternary", "=", Jumlah(true)); // output = 100
Penjelasan udah oke sih, tapi karena materi function no setelahnya jangan dimasukin dulu function ke materi ini

2021-10-05 05:52 UTC, hendraaagil commented
sepertinya ini duplicate, sudah ada di file: [basic/003_operator/ternaryOperator.js](https://github.com/bellshade/Javascript/blob/main/basic/003_operator/ternaryOperator.js)

2021-10-05 06:08 UTC, AndriP8 commented
> sepertinya ini duplicate, sudah ada di file: [basic/003_operator/ternaryOperator.js](https://github.com/bellshade/Javascript/blob/main/basic/003_operator/ternaryOperator.js) pull request: #56

Oiya, maaf kak kurang teliti baca isi repo nya

2021-10-05 06:34 UTC, nomadkode commented
akan di close yaa karena duplicate @AndriP8 . terima kasih sudah mencoba berkontribusi di bellshade. 👍🏼

2021-10-05 06:34 UTC, closed without merging